### ISSUE TITLE
(IoT): CfnAuthorizerProps.TokenSigningPublicKeys not generated in template

### ISSUE THREAD

**Issue by DennisNurtio** [aws/aws-cdk#11963]
**link to reference doc page**
https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.IoT.CfnAuthorizerProps.html#Amazon_CDK_AWS_IoT_CfnAuthorizerProps_TokenSigningPublicKeys
and 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-authorizer-tokensigningpublickeys.html

**describe your issue**
I am unable to get the `Amazon.CDK.AWS.IoT.CfnAuthorizerProps.TokenSigningPublicKeys` working in the .NET CDK. Please describe the C# type that should be used to call the setter of this property. 

**example**
```
    var au = new CfnAuthorizer(
                stack,
                "IotAuthorizer",
                new CfnAuthorizerProps
                {
                    AuthorizerFunctionArn = f.FunctionArn,
                    TokenKeyName = "token",
                    TokenSigningPublicKeys = new Dictionary<string, string>() { { "FIRST_KEY", "-----BEGIN PUBLIC KEY-----\nMI...AB\n-----END PUBLIC KEY-----\n" } },
                    SigningDisabled = false,
                    AuthorizerName = "TokenAuthorizer",
                });
```
Results in the following when cdk deploy is executed:
`"IotAuthorizer Invalid request provided: Token signing keys map for authorizer TokenAuthorizer cannot be null or empty. There must be at least one and at most two token signing public keys in the map".`

---

This is a 📕 documentation issue

**Comment by NGL321** [comment]
Hey @DennisNurtio,

Thanks for reporting this! I have investigated and I was able to reproduce your exception. Based on what I can tell from the lackluster [Cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-authorizer-tokensigningpublickeys.html) and the inconsistent CDK documentation ([.NET](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.IoT.CfnAuthorizer.html#Amazon_CDK_AWS_IoT_CfnAuthorizer_TokenSigningPublicKeys), [General](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iot.CfnAuthorizer.TokenSigningPublicKeysProperty.html), [Typescript](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-iot/cfnauthorizer.html)), I can pretty confidently indicate this is an issue with the Cloudformation resource spec (a premium support engineer was able to deploy a hand-built cfn template to accomplish the same task).

That said, we will cut a ticket to the Cfn team and keep this issue updated (Omkar, please put ticket number here when submitted so we can track it).

Unfortunately, since this is an L1 I dont have a good easy avenue for a workaround, but please let me know if there anything else I can do.

😸 😷

**Comment by DennisNurtio** [comment]
Thanks for investigating. 

For completeness, I have a case running at AWS Support center: 7703034011. But they are unable to help and referred me to this issue tracker.

**Comment by NGL321** [comment]
Root cause has been determined, Cloudformation team is working on a fix. I will update here when it is done. Then you will just have to wait for the next CDK release and this problem should self-resolve.

You will want to check documentation, the type used for passing the parameter will have changed.

**Comment by timmattison** [comment]
Has this been fixed? I saw that the CloudFormation resource specification update to v23.0.0 (commit a7a2236367f8f01b00b6d90f1d3fe7bf674b1aee) appears to fix this but I don't see it in the 1.84.0 release of CDK.

**Comment by skinny85** [comment]
Hey @timmattison ,

CloudFormation specification version `23.0.0` was released in [CDK `1.85.0`](https://github.com/aws/aws-cdk/releases/tag/v1.85.0), so updating to that version, or any later, should fix the issue.

Let me know if it works!


Thanks,
Adam

**Comment by DennisNurtio** [comment]
@skinny85 I have updated to CDK 1.86.0 and I am now able to use the `Amazon.CDK.AWS.IoT.CfnAuthorizerProps.TokenSigningPublicKeys` property. And the result in the Console looks correct.

I did not test the `Amazon.CDK.AWS.IoT.CfnAuthorizer.TokenSigningPublicKeys` property. Not sure where this key would end up.

The documentation of the property is still not updated, so for anybody that is using the C# version:
Amazon.CDK.AWS.IoT.CfnAuthorizerProps.TokenSigningPublicKeys is a `new Dictionary<string, string>` where the `key` is the name of the token, and the `value` is the token. And I am not sure, but I think the newlines in the token should be '\n'. 

And if somebody updates the docs, it might be nice to specify that the Amazon.CDK.AWS.IoT.CfnAuthorizerProps.Status property can be 'INACTIVE' or 'ACTIVE' (case sensitive, all-caps).

Thanks for you help so far.

Best regards,
Dennis

**Comment by timmattison** [comment]
This is working for me now. Thanks!

**Comment by skinny85** [comment]
Awesome, glad it's working now!

Let us know if you need anything else from us for this issue.
