### ISSUE TITLE
DynamoDB: Creation of Global table with CDK 1.77.0 Fails

### ISSUE THREAD

**Issue by juanheyns** [aws/aws-cdk#12113]
Updating a DynamoDB table (us-east-1) to create a global table fails with the following error in the CloudFormation console: `Response is not valid JSON`

### Reproduction Steps

    config.secondaryRegion = 'us-west-1'
    const tableKey = {
        partitionKey: {
          name: 'PK',
          type: dynamodb.AttributeType.STRING
        },
        sortKey: {
          name: 'SK',
          type: dynamodb.AttributeType.STRING
        }
      }

      const table = new dynamodb.Table(this, config.tableId, {
        tableName: config.tableName,
        billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
        replicationRegions: [config.secondaryRegion],
        removalPolicy: cdk.RemovalPolicy.RETAIN,
        ...tableKey
      })

### What did you expect to happen?

DynamoDB table should have streams enabled and a replica of the table should be created in the specified region (us-west-1)

### What actually happened?

Received the following error in CloudFormation console: `Response is not valid JSON`

### Environment

  - **CDK CLI Version**: 1.77.0 (build a941c53)
  - **Framework Version**: 1.77.0
  - **Node.js Version**: v12.18.3
  - **OS**: Ubuntu 16.04. 7 LTS (Xenial Xerus)
  - **Language (Version)**: TypeScript (4.0.3)

### Other

Contacted AWS Premium Support and got the following response:

To investigate the issue, I checked the Cloudformation stack “api-resources-v1-develop/43d62400-8604-11ea-b128-0eba1c1b0c34” and that shows custom resource 'apiresourcesauthconfigv1developReplicauswest150E65633' failed to respond to CloudFormation with a valid JSON response. Please understand custom resource in CDK is outside of the scope of AWS Support and thus we will not be able to help you troubleshoot the same.

However, in order to fix this issue I would suggest you to print the variable responsible for sending the response back to CloudFormation to the output first before sending the response to CloudFormation. This way you will be able to see exactly why the response data is not in a valid JSON format. In order to read more about this, please check these[1][2][3] documentation and examples.

I hope this email helps. Should you have any additional queries , please feel free to write back and I will be happy to help further!
 Hope you have a good day.

== References ==
[1] https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html 
[2] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html 
[3] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html 

We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @juanheyns . Can you also fill some of the details?

1. What's `config.secondaryRegion`?
2. What's in `...tableKey`?

Thanks,
Adam

**Comment by juanheyns** [comment]
```
    config.secondaryRegion = 'us-west-1'
    const tableKey = {
        partitionKey: {
          name: 'PK',
          type: dynamodb.AttributeType.STRING
        },
        sortKey: {
          name: 'SK',
          type: dynamodb.AttributeType.STRING
        }
      }
```

**Comment by juanheyns** [comment]
This was an update to a resource, so the table existed before adding the `replicationRegions` attribute.

**Comment by skinny85** [comment]
What region is the primary Table in?

**Comment by juanheyns** [comment]
us-east-1

**Comment by skinny85** [comment]
Thanks. Let me try to reproduce it.

**Comment by skinny85** [comment]
Unfortunately, I wasn't able to reproduce it 😕. Here's what I did:

I started with this:

```ts
import * as cdk from '@aws-cdk/core';
import * as dynamodb from '@aws-cdk/aws-dynamodb';

export class DynamoDbGlobalStack extends cdk.Stack {
    constructor(scope: Construct, idL string, props?: cdk.StackProps) {
        super(scope, id, props);

        const tableKey = {
            partitionKey: {
                name: 'PK',
                type: dynamodb.AttributeType.STRING
            },
            sortKey: {
                name: 'SK',
                type: dynamodb.AttributeType.STRING
            }
        };
        const table = new dynamodb.Table(this, 'Table', {
            billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            ...tableKey,
        });
    }
}
```

I deployed that, and then changed to:

```ts
import * as cdk from '@aws-cdk/core';
import * as dynamodb from '@aws-cdk/aws-dynamodb';

export class DynamoDbGlobalStack extends cdk.Stack {
    constructor(scope: Construct, idL string, props?: cdk.StackProps) {
        super(scope, id, props);

        const tableKey = {
            partitionKey: {
                name: 'PK',
                type: dynamodb.AttributeType.STRING
            },
            sortKey: {
                name: 'SK',
                type: dynamodb.AttributeType.STRING
            }
        };
        const table = new dynamodb.Table(this, 'Table', {
            billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
            replicationRegions: ['us-west-1'],
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            ...tableKey,
        });
    }
}
```

Deployed again, and everything worked... (I used the same region for the Stack, `us-east-1`)

Can you try the above, and see if you get the error again?

**Comment by juanheyns** [comment]
I looked at my logs again, I think what was happening is the table name changed at the same time. I will try again without changing the table name and see if that works.

**Comment by kbroniek** [comment]
@skinny85 I had the same issue. I created a new global table on us-east-1 and replicated it on eu-central-1. I have 3 environments and in two of them it deployed successfully but in one environment it failed during creating the replication. I had the same error `Response is not valid JSON`. But when I repeated the deployment, I haven't seen any issue. It was weird and would be good to solve this issue.
I use CDK version 1.80.0.
This is what I use:
``` typescript
export class DynamoDbGlobalStack extends cdk.Stack {
    constructor(scope: Construct, idL string, props?: cdk.StackProps) {
        super(scope, id, props);

        const testTableDynamoDb = new Table(this, "TestTable", {
            partitionKey: { name: "id", type: AttributeType.STRING },
            encryption: TableEncryption.AWS_MANAGED,
            replicationRegions: replicationRegions,
            billingMode: BillingMode.PROVISIONED,
            readCapacity: 5,
            writeCapacity: 1,
        });

        testTableDynamoDb
            .autoScaleReadCapacity({ minCapacity: 5, maxCapacity: 10 })
            .scaleOnUtilization({ targetUtilizationPercent: 75 });
        testTableDynamoDb
            .autoScaleWriteCapacity({ minCapacity: 1, maxCapacity: 10 })
            .scaleOnUtilization({ targetUtilizationPercent: 75 });
    }
}
```

**Comment by skinny85** [comment]
@kbroniek any chance of getting some more detailed logs of this? Without something more than "Response is not valid JSON", it will be really difficult to nail this problem down...

Do you still have the logs for the Lambda that implements the Custom Resource, for example?

**Comment by kbroniek** [comment]
@skinny85 Thank you for your answer. I checked and found more info:
```
13:27:19   36/39 | 12:27:18 PM | CREATE_IN_PROGRESS   | Custom::DynamoDBReplica                     | UserTable/Replicaeu-central-1/Default (UserTableReplicaeucentral1B491452D) 
13:27:35   36/39 | 12:27:33 PM | CREATE_FAILED        | Custom::DynamoDBReplica                     | UserTable/Replicaeu-central-1/Default (UserTableReplicaeucentral1B491452D) Response is not valid JSON
13:27:35  	new CustomResource (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/@aws-cdk/core/lib/custom-resource.ts:119:21)
13:27:35  	\_ Table.createReplicaTables (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/@aws-cdk/aws-dynamodb/lib/table.ts:1473:29)
13:27:35  	\_ new Table (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/@aws-cdk/aws-dynamodb/lib/table.ts:1134:12)
13:27:35  	\_ BaseStack.createUserDynamoDB (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/lib/stack-prototype.ts:73:30)
13:27:35  	\_ new BaseStack (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/lib/stack-prototype.ts:35:32)
13:27:35  	\_ createStack (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/bin/cdk.ts:60:16)
13:27:35  	\_ /home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/bin/cdk.ts:31:32
13:27:35  	\_ Object.<anonymous> (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/bin/cdk.ts:39:7)
13:27:35  	\_ Module._compile (internal/modules/cjs/loader.js:1015:30)
13:27:35  	\_ Module.m._compile (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/index.ts:1056:23)
13:27:35  	\_ Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
13:27:35  	\_ Object.require.extensions.<computed> [as .ts] (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/index.ts:1059:12)
13:27:35  	\_ Module.load (internal/modules/cjs/loader.js:879:32)
13:27:35  	\_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
13:27:35  	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
13:27:35  	\_ main (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/bin.ts:198:14)
13:27:35  	\_ Object.<anonymous> (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/bin.ts:288:3)
13:27:35  	\_ Module._compile (internal/modules/cjs/loader.js:1015:30)
13:27:35  	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
13:27:35  	\_ Module.load (internal/modules/cjs/loader.js:879:32)
13:27:35  	\_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
13:27:35  	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
13:27:35  	\_ /usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```
Moreover, I found weird behavior. Because when an error has occurred, all resources should also be deleted, but there is another error related to deleting a table

```
13:28:00    4/39 | 12:27:55 PM | DELETE_FAILED        | Custom::DynamoDBReplica                     | UserTable/Replicaeu-central-1/Default (UserTableReplicaeucentral1B491452D) Failed to delete resource. Replica specified in the Replica Update or Replica Delete action of the request was not found.
13:28:00  
13:28:00  Logs: /aws/lambda/stage-iad-cloud-authenticat-OnEventHandler42BEBAE0-1F7W8YK4JA4NG
13:28:00  
13:28:00      at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
13:28:00      at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
13:28:00      at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
13:28:00      at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
13:28:00      at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
13:28:00      at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
13:28:00      at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
13:28:00      at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
13:28:00      at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
13:28:00      at Request.callListeners (/var/runtime/n
13:28:00  	new CustomResource (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/@aws-cdk/core/lib/custom-resource.ts:119:21)
13:28:00  	\_ Table.createReplicaTables (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/@aws-cdk/aws-dynamodb/lib/table.ts:1473:29)
13:28:00  	\_ new Table (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/@aws-cdk/aws-dynamodb/lib/table.ts:1134:12)
13:28:00  	\_ BaseStack.createUserDynamoDB (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/lib/stack-prototype.ts:73:30)
13:28:00  	\_ new BaseStack (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/lib/stack-prototype.ts:35:32)
13:28:00  	\_ createStack (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/bin/cdk.ts:60:16)
13:28:00  	\_ /home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/bin/cdk.ts:31:32
13:28:00  	\_ Object.<anonymous> (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/bin/cdk.ts:39:7)
13:28:00  	\_ Module._compile (internal/modules/cjs/loader.js:1015:30)
13:28:00  	\_ Module.m._compile (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/index.ts:1056:23)
13:28:00  	\_ Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
13:28:00  	\_ Object.require.extensions.<computed> [as .ts] (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/index.ts:1059:12)
13:28:00  	\_ Module.load (internal/modules/cjs/loader.js:879:32)
13:28:00  	\_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
13:28:00  	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
13:28:00  	\_ main (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/bin.ts:198:14)
13:28:00  	\_ Object.<anonymous> (/home/ubuntu/workspace/tication-global-data-cdk_develop@stage-iad/node_modules/ts-node/src/bin.ts:288:3)
13:28:00  	\_ Module._compile (internal/modules/cjs/loader.js:1015:30)
13:28:00  	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
13:28:00  	\_ Module.load (internal/modules/cjs/loader.js:879:32)
13:28:00  	\_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
13:28:00  	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
13:28:00  	\_ /usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

After that I have leftovers, I mean the table still exists but without replication.

**Comment by kbroniek** [comment]
Finally, I found the details in CloudWatch maybe it will be helpful.
```
2021-01-26T12:27:32.129Z	154a6b8c-85a5-4022-9381-f674221e5a9b	INFO	[provider-framework] user function response: {
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST",
    "Payload": "{\"errorType\":\"ValidationException\",\"errorMessage\":\"Failed to describe limits in region: ‘EU_CENTRAL_1’. User is missing the following permissions: ‘dynamodb:DescribeLimits’.\",\"trace\":[\"ValidationException: Failed to describe limits in region: ‘EU_CENTRAL_1’. User is missing the following permissions: ‘dynamodb:DescribeLimits’.\",\"    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)\",\"    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\",\"    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\",\"    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)\",\"    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\",\"    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\",\"    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\",\"    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\",\"    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)\",\"    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\"]}"
} object

2021-01-26T12:27:32.130Z	154a6b8c-85a5-4022-9381-f674221e5a9b	INFO	[provider-framework] user function threw an error: Unhandled

2021-01-26T12:27:32.130Z	154a6b8c-85a5-4022-9381-f674221e5a9b	INFO	[provider-framework] CREATE failed, responding with a marker physical resource id so that the subsequent DELETE will be ignored
```

**Comment by skinny85** [comment]
Thanks so much @kbroniek , that's super helpful!

**Comment by OliverLonghi** [comment]
Hi, I'm facing this error too. Can you give a follow up on how to solve it? The interesting thing to me is that my CR worked fine in my beta/dev environment but failed to deploy in the gamma/pre-prod account.

The Resource ReportTableReplicauswest2 creation is interrupted with this error \"Response is not valid JSON\". And looking into the logs of the created lambda (/aws/lambda/DynamoDbStack-gamma-awscdka-OnEventHandler42BEBAE0-NjX1v1Ik4Rub) I see this error:

`2022-11-08T00:44:49.850Z\ta723fbd4-5096-4ac6-8dab-6c4be4f1c4ed ERROR\tInvoke Error {\"errorType\":\"ValidationException\",\"errorMessage\":\"Failed to describe limits in region: 'US_WEST_2'. User is missing the following permissions: 'dynamodb:DescribeLimits'.\",\"code\":\"ValidationException\",\"message\":\"Failed to describe limits in region: 'US_WEST_2'. User is missing the following permissions: 'dynamodb:DescribeLimits'.\",\"time\":\"2022-11-08T00:44:49.849Z\",\"requestId\":\"DIPP7I6P2O2PPRU4BBG3BTKIQRVV4KQNSO5AEMVJF66Q9ASUAAJG\",\"statusCode\":400,\"retryable\":false,\"retryDelay\":25.854823257468173,\"stack\":[\"ValidationException: Failed to describe limits in region: 'US_WEST_2'. User is missing the following permissions: 'dynamodb:DescribeLimits'.\",\" at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)\",\" at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\",\" at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\",\" at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)\",\" at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\",\" at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\",\" at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\",\" at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\",\" at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)\",\" at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\"]}`


The rollback also fails with this error:
`Received response status [FAILED] from custom resource. Message returned: Replica specified in the Replica Update or Replica Delete action of the request was not found. Logs: /aws/lambda/DynamoDbStack-gamma-awscdka-OnEventHandler42BEBAE0-NjX1v1Ik4Rub at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: 5b0514b8-c7d5-4040-bd20-12e29aa32452)`

My code:

```
if (props.stage.region === AwsRegion.UsEast1) {
    const reportTable : DynamoDbConstruct = new DynamoDbConstruct(this, `ReportTable`, {
        stage: props.stage,
        tableName: `${JOB_REPORT_TABLE_NAME}-${props.stage.name}`,
        partitionKey: JOB_REPORT_TABLE_PARTITION_KEY,
        sortKey: JOB_REPORT_TABLE_SORT_KEY,
        readCapacity: {min: 5, max: 50},
        writeCapacity: {min: 5, max: 50},
        replicationRegions: [AwsRegion.UsWest2]
    });
}

...

export class DynamoDbConstruct extends Construct {
    public readonly table: Table;

    constructor(scope: Construct, id: string, props: DynamoDbProps) {
        super(scope, id);

        this.table = new Table(this, id, {
                tableName: `${props.tableName}`,
                partitionKey: {
                    name: `${props.partitionKey}`,
                    type: AttributeType.STRING,
                },
                sortKey: props.sortKey ? {
                    name: `${props.sortKey}`,
                    type: AttributeType.STRING,
                } : undefined,
                billingMode: BillingMode.PROVISIONED,
                readCapacity: props.readCapacity.min,
                writeCapacity: props.writeCapacity.min,
                replicationRegions: props.replicationRegions
        });

        const readAutoScale = this.table.autoScaleReadCapacity({
            minCapacity: props.readCapacity.min,
            maxCapacity: props.readCapacity.max,
        });
        readAutoScale.scaleOnUtilization({
            targetUtilizationPercent: 70,
        });

        const writeAutoScale = this.table.autoScaleWriteCapacity({
            minCapacity: props.writeCapacity.min,
            maxCapacity: props.writeCapacity.max,
        });
        writeAutoScale.scaleOnUtilization({
            targetUtilizationPercent: 70,
        });
    }
}
```

**Comment by OliverLonghi** [comment]
Btw, I've also cut a ticket to AWS Premium Support and they also said that CDK is out of their scope.

**Comment by oscar-dela** [comment]
Same here. I also encounter same error as @OliverLonghi described.

**Comment by jwestbrook** [comment]
I realize this issue has been open for a while - but it came up when I was searching for my error "Failed to describe limits". I'm not using CDK but simply CloudFormation. To solve the limits error I needed to let the primary table create with streams enabled, and then push an update to the CloudFormation Stack with the additional replica region added. I could not enable streams and add the replica region in the same update/create. I hope this information helps someone.
