### ISSUE TITLE
(@aws-cdk/aws-cloudfront): lambda@edge function execution role is missing service principal 'edgelambda.amazonaws.com'

### ISSUE THREAD

**Issue by Jeansse** [aws/aws-cdk#12492]
When creating a web distribution with a an lambda@edge function the created service role does not allow the "edgelambda.amazonaws.com" service principal to assume the role. When deploying the stack it fails with the following error message:

```
The function execution role must be assumable with edgelambda.amazonaws.com as well as lambda.amazonaws.com principals. Update the IAM role and try again. Role: arn:aws:iam::1111111111111:role/edge-lambda-stack-eu-cen
```

I did create the stack in `eu-central-1` as this is my default region. As the lambda@edge function needs to be created in `us-east-1` the cdk automatically synthesises my construct to 2 stacks. Because of that I wasn't able to just add the correct policy to the service role by calling `edgeAuthorizerHandler.addToRolePolicy(...)` as this would lead to the following error message:

```
Resolution error: Cannot use resource 'WebAppStack/edgeAuthorizerExecutionRole-1' in a cross-environment fashion
``` 

### Reproduction Steps

``` Typescript
import * as cdk from '@aws-cdk/core';
import * as cloudfront from '@aws-cdk/aws-cloudfront';
import * as origins from '@aws-cdk/aws-cloudfront-origins';
import * as lambda from '@aws-cdk/aws-lambda';

import { Bucket } from '@aws-cdk/aws-s3';
import { Certificate } from '@aws-cdk/aws-certificatemanager';

export class WebAppStack extends cdk.Stack {
  static readonly certificateArn = 'arn:aws:acm:us-east-1:11111111111:certificate/ddddd-ddddd-ddddd-dddd-dddd';

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = Bucket.fromBucketAttributes(this, 'MySrcBucket', {
        bucketArn: 'arn:aws:s3:::bucket-name',
    });
    
    const certificateArn = WebAppStack.certificateArn;
    const certificate = Certificate.fromCertificateArn(this, 'WebCertificate', certificateArn);          
    
    const edgeAuthorizerHandler = new cloudfront.experimental.EdgeFunction(this, 'EdgeAuthorizer', {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'edge-authorizer.handler',
      code: lambda.Code.fromAsset('lambda'),      
    });
    
    const distribution = new cloudfront.Distribution(this, 'WebDistribution', {
      certificate: certificate,
      domainNames: [ 'example.com' ],
      defaultBehavior: {
        origin: new origins.S3Origin(bucket),        
        edgeLambdas: [
          {
            functionVersion: edgeAuthorizerHandler.currentVersion,
            eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST,
          }
        ],
      },      
    });
  }
}
```

### What did you expect to happen?

EdgeAuthorizerHandler Service role is created with both service principals.

``` RAML
"EdgeAuthorizerServiceRole5D663D2D": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service":  [ 
                  "lambda.amazonaws.com",
                  "edgelambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
       ...
    }, 
```

### What actually happened?

``` RAML
"EdgeAuthorizerServiceRole5D663D2D": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
       ...
    }, 
```

**Note: When manually editing the trust relationship of the role in the AWS console, the stack deploys successfully** 

### Environment

  - **CDK CLI Version  : 1.84.0 (build 866c8dc)**
  - **Framework Version:**
  - **Node.js Version: v12.19.0.**
  - **OS               :  MacOS 10.14.6**
  - **Language (Version): Typescript 4.1.3**

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report and detailed repro steps! However, I can't seem to repro the error myself. Taking your example and synthesizing it gives me the following for the role:

```
    "EdgeAuthorizerServiceRole5D663D2D": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              }
            },
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "edgelambda.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
              ]
            ]
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "edge-lambda-stack-eu-west-2/EdgeAuthorizer/ServiceRole/Resource"
      }
    },
```

You'll see both service principals are there, albeit in different statements rather than a single statement (as your expected example shows). This is due to a quirk in the underlying implementation, but the two are equivalent in how they're evaluated.

This is the code in EdgeFunction which adds the service role:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L236-L243

Can you confirm your synthesized template doesn't include the edgelambda.amazonaws.com service principal at all? Is there anything else here at play (e.g., a permissions boundary) that might be altering the outcome?

**Comment by Jeansse** [comment]
@njlynch Thanks for the quick response. I checked again and can confirm that I can't find the `edgelambda.amazonaws.com` service principal at all. I guess you tried to deploy the stack to a region other than 'us-east-1' right? 

Just to be sure I deleted the `cdk.out` directory and ran `cdk synth` again and got the same result.
I do explicitly set the environment (account + region) when initialising the stack. Not sure if that has an influence.

``` Typescript
const webStack = new WebAppStack(app, 'WebAppStack', {
  env: {
    account: env.account,
    region: env.region
  },
});
```

Potentially it only happens when you deploy to `eu-central-1` although that would be hard to explain I guess. I do have `admin` privilege so I would exclude that it comes from a permission - or are you referring to other permission boundaries?

**Comment by njlynch** [comment]
Very odd. What are the modules and version(s) of the CDK that you're using? Just about the only thing I can imagine causing this is if the versions are misaligned, and the `role instanceof iam.Role` check in the code failing. Can you double-check everything's the same version (e.g., check `package.json`, `npm ci`).

**Comment by Jeansse** [comment]
I'm using cdk version 1.84.0 (installed globally with npm -g). I also ran `npm ci` again.
See below my `package.json` dependencies :

``` RAML
"devDependencies": {
    "@aws-cdk/assert": "^1.84.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "@aws-cdk/aws-certificatemanager": "^1.84.0",
    "@aws-cdk/aws-cloudfront": "^1.84.0",
    "@aws-cdk/aws-cloudfront-origins": "^1.84.0",
    "@aws-cdk/aws-iam": "^1.84.0",
    "@aws-cdk/aws-lambda": "^1.84.0",
    "@aws-cdk/aws-route53": "^1.84.0",
    "@aws-cdk/aws-route53-targets": "^1.84.0",
    "@aws-cdk/aws-s3": "^1.84.0",
    "@aws-cdk/core": "^1.84.0",
    "source-map-support": "^0.5.16"
  }
```

**Comment by robertd** [comment]
FWIW... I just deployed CF distro with S3 origin and L@E function from scratch and I couldn't reproduce the error.

**Comment by Jeansse** [comment]
@njlynch @robertd Thanks for your efforts. Also started out with a fresh empty directory and couldn't reproduce it.

So, I just deleted my whole repo and re-initialised it with `cdk init` and started adding code snippet by code snippet and now it works. Still not sure what the problem was but I started the repo using v1.83 and just yesterday did the upgrade to v1.84. 

Thanks for your support and sorry for bothering.

**Comment by njlynch** [comment]
Must've been random solar flares. 🤷   Glad it's working now!

**Comment by robertd** [comment]
>Thanks for your efforts. Also started out with a fresh empty directory and couldn't reproduce it.
>So, I just deleted my whole repo and re-initialised it with cdk init and started adding code snippet by code snippet and now it works. Still not sure what the problem was but I started the repo using v1.83 and just yesterday did the upgrade to v1.84.
>Thanks for your support and sorry for bothering.

@Jeansse Glad you got it working. Usually what I do when I'm upgrading cdk versions is I delete the `package-lock.json`, `node_modules`, `cdk.out`. Then I update `package.json` with new cdk version and run `npm i`. Also, from time to time I create a test cdk app to check for any `package.json` changes/dependency updates.

Hope this helps.

**Comment by Jeansse** [comment]
@robertd Makes sense. Thanks for the input. I always hesitate to delete `package-lock.json`, however in this case I guess this would have helped.
