### ISSUE TITLE
lambda: corrupt zip archive asset produced when using node v15.6

### ISSUE THREAD

**Issue by machielg** [aws/aws-cdk#12536]
_Update from the CDK team_

When using local assets with the lambda module using the [`Code.fromAsset()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html#static-fromwbrassetpath-options) API, deployment of new assets (during `cdk deploy`) will fail with the error - "Uploaded file must be a non-empty zip"

We have confirmed this issue manifests when using node engine v15.6. The root cause is being tracked by node - https://github.com/nodejs/node/issues/37027. For the time being, use a node engine < `15.6`.

If you have encountered this issue, you need to do three things to resolve this -
1. Downgrade to a node version < `15.6`. You can see what you're current node version is by running `node --version`.
2. Delete the cached asset in the `cdk.out/` directory. You could safely delete the entire directory, and the correct assets and templates will be re-generated during the next run of `cdk synth` or `cdk deploy`. 
3. Delete the previously uploaded asset from the staging bucket. The S3 key of the asset will be prefixed with `asset/` and have the hash of the asset. The hash of the asset can be found in your application's CloudFormation template.
  The staging bucket can be obtained by running the following command - 
  ```bash
   aws cloudformation describe-stack-resources --stack-name CDKToolkit --logical-resource-id StagingBucket  --query 'StackResources[].PhysicalResourceId'
  ```
  
-------

_Original issue filed below_

When doing
```typescript
const fillFn = new lambda.Function(this, "Zip2GzipSQSFill", {
    code: lambda.Code.fromAsset("lib/python"),
    runtime: lambda.Runtime.PYTHON_3_7,
    handler: "mylambda.handler"
    }
);
```

my file is here (relative to root of the CDK project):
lib/python/mylambda.py

its contents:
```python
def handler(event, context):
    print("HELLO AWS")
```

I get the error:

Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: fcfaf553-70d3-40b8-85d2-a15f6c3bcef0; Proxy: null)

### Reproduction Steps

run `cdk deploy`
### What did you expect to happen?

the Lambda is created in AWS

### What actually happened?

An zip file is uploaded to the CDK staging bucket, there is a zip file there with my python file, but that file has no contents

### Environment

  - **CDK CLI Version  :** 1.85.0 or 1.83.0
  - **Framework Version:** 1.83.0
  - **Node.js Version:** 15.6.0 
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (4.1.3)

### Other

I'm suspecting it's a nodejs/library problem, in that some library is producing this invalid zip file but I have no evidence of this.

--- 

This is :bug: Bug Report

**Comment by joel-aws** [comment]
@machielg -- could you update the title, maybe to "Uploaded Zips of Functions are Empty".

I'm running into the same issue and want to ensure it's visible.

**Comment by joel-aws** [comment]
Running into the same issue now with `aws_s3_deployment` on 1.84.0 and 1.85.0:

![image](https://user-images.githubusercontent.com/57411589/104775773-eec2c080-5746-11eb-8460-da4a08170191.png)

**Comment by hoegertn** [comment]
I had the same issue today with a customer using the serverless framework. So it might be something outside CDK, also.

**Comment by joel-alejandre** [comment]
> I had the same issue today with a customer using the serverless framework. So it might be something outside CDK, also.

I think you're right... Although I just tried it with us-east-1 and us-west-1 to no avail; so I don't think it's with AWS infra either. Curious where the issue is, then.

**Comment by joel-aws** [comment]
> I had the same issue today with a customer using the serverless framework. So it might be something outside CDK, also.

I think you're right... Although I just tried it with us-east-1 and us-west-1 to no avail; so I don't think it's with AWS infra either. Curious where the issue is, then.

**Comment by buddhabuddy** [comment]
Very similar issue, zip downloaded shows CRC errors but files are present and 7zip can recover them.

**Comment by DrCake** [comment]
I didn't have issues with deploying the `aws_s3_deployment` function itself on 1.83, but did find that the files uploaded to S3 were all empty. Updating to 1.85 I now get the error in https://github.com/aws/aws-cdk/issues/12536#issuecomment-761182906

**Comment by hoegertn** [comment]
What versions of Node do y'all use? As a wild guess, I think it might be a node 15 issue.

**Comment by joel-aws** [comment]
> What versions of Node do y'all use? As a wild guess, I think it might be a node 15 issue.

v15.6.0

**Comment by machielg** [comment]
I updated to node 15.6.0 just yesterday when also this bug started so it’s a likely suspect. Downgrading to node 14 didn’t seem to help though. I’m planning to run it in a docker container to isolate the library responsible.

**Comment by DrCake** [comment]
> What versions of Node do y'all use? As a wild guess, I think it might be a node 15 issue.

I’m having the same issue on Node 12

**Comment by machielg** [comment]
I tested with several node versions, I can't get it to work with any version (10, 14, 15). 

It's clear that zipping of my asset dir with the python code isn't triggered, the zip file with the code isn't created. 

I just updated all packages and it seems to work again.

**Comment by joel-aws** [comment]
> I just updated all packages and it seems to work again.

Which packages did you update and using what commands?

**Comment by machielg** [comment]
> > I just updated all packages and it seems to work again.
> 
> Which packages did you update and using what commands?

I got an update for @types/node to version 14.14.21 which was released very recently.

**Comment by danilobuerger** [comment]
I had the same issue after upgrading to 15.6.0. Downgrading (and deleting cdk-out/.cache and deleting the zip files on the s3 bucket) worked!

**Comment by machielg** [comment]
> I had the same issue after upgrading to 15.6.0. Downgrading (and deleting cdk.out/.cache and deleting the zip files on the s3 bucket) worked!

Perhaps you can list your relevant package versions?

**Comment by danilobuerger** [comment]
@machielg Which package version?

**Comment by machielg** [comment]
@danilobuerger node types

**Comment by danilobuerger** [comment]
@machielg They have nothing to do with it... as I wrote downgrading node itself and deleting the caches is enough.

**Comment by machielg** [comment]
@danilobuerger that didn’t work for me so I’m trying to find out what fixed it

**Comment by danilobuerger** [comment]
@machielg you probably did not clear the caches.

**Comment by machielg** [comment]
@danilobuerger which caches?

**Comment by danilobuerger** [comment]
@machielg please read above, I mentioned it in my first comment here....

**Comment by therealsebo** [comment]
> I had the same issue after upgrading to 15.6.0. Downgrading (and deleting cdk.out/.cache and deleting the zip files on the s3 bucket) worked!

Thx @danilobuerger ! Downgrading to Node@14, deleting the cdk dir and Remove Zip from S3 worked for me

**Comment by danilobuerger** [comment]
@therealsebo Awesome! It seems to me that everything including 15.5.1 is working.

**Comment by PierreKiwi** [comment]
I am also facing this issue.
I managed to make it work by clearing the asset in S3 and deleting cdk.out (not sure what .cache is) but it s failing again.

**Comment by machielg** [comment]
> I am also facing this issue.
> I managed to make it work by clearing the asset in S3 and deleting cdk.out (not sure what .cache is) but it s failing again.

it was working for me yesterday, but this morning it failed again. The zip file created by CDK contains all the files, but they are all empty. The issue seems to be coming from the archiver lib:
https://github.com/archiverjs/node-archiver/issues/491

**Comment by machielg** [comment]
Downgrading to Node v15.5.1 _and_ doing a proper clean seems to fix the problem.

**Comment by PierreKiwi** [comment]
Thanks @machielg. I downgraded to Node v14.15.4 and to node-archiver 5.1.0. So far it is looking OK now.

**Comment by cmckni3** [comment]
Ran into this issue today with node v12.20.0. Downgraded to CDK version 1.74.0 to get it working again.

**Comment by cmckni3** [comment]
> I am also facing this issue.
> I managed to make it work by clearing the asset in S3 and deleting cdk.out (not sure what .cache is) but it s failing again.

This worked for me as well. Frustrating.

**Comment by MHacker9404** [comment]
I'm not seeing this issue with Lambda::NodejsFunction (typescript) 1.85.0, Node 15.5.0.

**Comment by cmckni3** [comment]
@MHacker9404 @machielg why aren't you using an active LTS version of node.js?

**Comment by MHacker9404** [comment]
Because this is on my personal machine....

**Comment by cmckni3** [comment]
CDK 1.85.0 works for me on node v12.20.x.

**Comment by machielg** [comment]
> @MHacker9404 @machielg why aren't you using an [active LTS version of node.js](https://nodejs.org/en/about/releases/)?
> 
> ![image](https://user-images.githubusercontent.com/735717/105093423-54c18780-5a68-11eb-9e41-879688f8369a.png)

Good question, `brew` installs 15.x by default.

**Comment by MHacker9404** [comment]
I use NVM for Windows - so I have 3-4 different versions installed....

**Comment by cmckni3** [comment]
I use nvm on macOS. I have 3 major versions installed.

**Comment by kodemaniak** [comment]
I have this problem also with Node 14.15.4 and cdk 1.85.0. With 1.74.0 it works. Unfortunately 1.74.0 is missing a feature I require, so this is not a solution for me.

**Comment by jmpalomar** [comment]
> > @MHacker9404 @machielg why aren't you using an [active LTS version of node.js](https://nodejs.org/en/about/releases/)?
> > ![image](https://user-images.githubusercontent.com/735717/105093423-54c18780-5a68-11eb-9e41-879688f8369a.png)
> 
> Good question, `brew` installs 15.x by default.
> 
> Is it possible for aws-cdk to specify the compatible/supported version(s)? So it doesn't install on node 15.x or gives a warning

You can do it:
`brew install node@14 && brew link node@14 --overwrite`

Anyway doing it did not work for me still checking how to fix this.

**Comment by brennick** [comment]
Having the same issue on a new M1 MacBook Air. Older versions (<15.x) of Node don't work on the new Macs and v15.6.0 is giving me this error when doing `cdk deploy`

**Comment by saksham** [comment]
Downgrading to node version 14 (from 15.6.0) worked for me for CDK version 1.85.0. I was getting same error saying `Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2993dbcd-474d-466b-a4d6-7abfd49af443; Proxy: null)` when trying to use `aws_cdk.aws_lambda_python.PythonFunction` with a lambda folder with poetry. The asset in `cdk.out` and the bucket had the correct zip file, but cloudformation failed to acknowledge that the file was there.

**Comment by phelucko** [comment]
Downgraded to node version 14 but still not working for me. The asset in the bucket was a non-empty zip.

**Comment by rudyhadoux** [comment]
Same here with sls deploy. Very cool...

**Comment by duntonr** [comment]
I was also experiencing this issue but finally got things working again with NodeJS `12.20.1` and CDK `1.85.0`.  I suspect it should also work for the latest 14.x LTS.

During initial troubleshooting, I tried several combinations of Node and CDK versions but no to avail, would always get the non-empty zip file error during deployment.  I had been clearing out the `cdk.out` folder but I was NOT clearing the zip files in the CDK bootstrap bucket on S3. Once I did that, it worked.

As may other commenters already pointed out, you **NEED** to clear **BOTH** your local `cdk.out` **AND** the offending zip files in the CDK bootstrap S3 bucket on AWS (or just deleted everything in the bootstrap bucket which is what I did).

It looks like the root issue is that the zip file names are simple hash checks and CDK is optimized to not bother reuploading the "same file" but "same" is detected just by filename, not by size or modification date.  As such, once you have this issue, your bootstrap buckets are "poisoned" for lack of a better term and won't work again unless you either A) clear the offending files in the S3 bucket, or just delete it all or B) modified your actual code enough to result in a new hash being generated (I suspect this could be a side effect for some troubleshooting).

**Comment by kodemaniak** [comment]
I can confirm what @duntonr wrote. Deleting the zip files from the bucket works using NodeJS 14.15.4.

**Comment by cmckni3** [comment]
Issue has returned for me on node v12.20.0 and CDK version 1.85.0.

**Comment by machielg** [comment]
I think the best solution is for the cdk cli to pin the archiver dependency to 5.1.0. The latest version seems to have timing issues.

**Comment by cmckni3** [comment]
> I think the best solution is for the cdk cli to pin the archiver dependency to 5.1.0. The latest version seems to have timing issues.

CDK 1.86.0 has timing issues?

**Comment by cmckni3** [comment]
I have a deployment running with CDK 1.86.0 right now.

**Comment by machielg** [comment]
> > I think the best solution is for the cdk cli to pin the archiver dependency to 5.1.0. The latest version seems to have timing issues.
> 
> CDK 1.86.0 has timing issues?

I mean archiver 5.2

**Comment by harrysolovay** [comment]
Confirmed––deleting the contents of the staging bucket solves the issue.

**Comment by mauricioharley** [comment]
I was struggling with his until found this GitHub issue. It worked for me after downgrading Node.JS to 14.5.4 with the commands provided by @jmpalomar.

I'm currently using CDK 1.86.0 (core and modules).

**Comment by chegger** [comment]
Using  `cdk 1.86` + `node:lts` docker image **DOES** work for me

Using `cdk 18.6` +  `node:latest` did **NOT** work.

**Comment by proligde** [comment]
Same here - I could fix the problem by rolling back to lts:

```
sudo npm install -g n
sudo n lts
```

**Comment by cmckni3** [comment]
> I have a deployment running with CDK 1.86.0 right now.

Same problem. Had to empty S3 bucket.

**Comment by robertd** [comment]
Same issue here... lts + cleanup did the trick. Luckily our CI/CD pipeline is using `node:lts-alpine` anyway so issue was only observed on dev boxes.

**Comment by NetaNir** [comment]
HI everyone!

Sorry about this :/.

As you can see the issue was not automatically assigned to one of the core team members, hence the delay in the response. If this ever happens I asked you kindly tag one of the core team on the issue, here is the list of GitHub id: https://github.com/aws/aws-cdk/blob/4871f4a1503bc2d82440e204e1c5b05f2ef26b7b/.mergify.yml#L9

Im going to look into this now.

**Comment by viventra** [comment]
@NetaNir, I am encountering the following error during a `cdk deploy`:
I upgraded to NodeJS v15.6.0 and cdk toolkit v1.86.0 (build a10cfcf) yesterday.

```
13/23 | 9:06:07 AM | CREATE_FAILED        | AWS::Lambda::Function       | ApimethodsHandler (ApimethodsHandlerD82FED6A) Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: c9b1645c-d3b4-4647-bcb2-26b250a22f10; Proxy: null)
        new Function (C:\Users\vx\AppData\Local\Temp\jsii-kernel-jWF0YQ\node_modules\@aws-cdk\aws-lambda\lib\function.js:133:26)
        \_ C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:3556:49
        \_ Kernel._wrapSandboxCode (C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:4040:16)
        \_ Kernel._create (C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:3556:26)
        \_ Kernel.create (C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:3300:21)
        \_ KernelHost.processRequest (C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:13119:28)
        \_ KernelHost.run (C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:13057:14)
        \_ Immediate._onImmediate (C:\Users\vx\AppData\Local\Temp\iuq34vgl.n2n\jsii-runtime.js:13060:37)
        \_ processImmediate (node:internal/timers:463:21)
```

The code that invokes the Lambda installation is in C#:

```
            // 2. Add the Lambda functions
            var Apimethods = new Function(this, "ApimethodsHandler", new FunctionProps
            {
                Runtime = Runtime.NODEJS_12_X, // execution environment
                Code = Code.FromAsset("resources"), // Code loaded from the "resources" directory
                Handler = "apimethods.handler" // file is "apimethods", function is "handler"
            });

```

When I run cdk deploy, 
the cdk.out folder has the apimethods.js Lambda source file under assets folder, 
the cdktoolkit-staging-xxx S3 bucket contains a 0 byte ZIP file under assets folder and I get the error as mentioned above.

I tried clearing the `cdk.out` folder and emptying the `cdktoolkit-staging-xxx` bucket as others have pointed out. The error occurs even after that. I would prefer a solution that doesn't require a NodeJS downgrade.

**Comment by christophgysin** [comment]
This seems to be caused by: https://github.com/archiverjs/node-archiver/issues/491

**Comment by ckhicks** [comment]
> Having the same issue on a new M1 MacBook Air. Older versions (<15.x) of Node don't work on the new Macs and v15.6.0 is giving me this error when doing `cdk deploy`
> 
> EDIT: I was able to get it working. Steps below...
> 
> 1. Use `nvm` for version management
> 2. Create copy of iTerm app, rename to `Rosetta iTerm` and update to `Open using Rosetta`
> 3. Open `Rosetta iTerm`, and run `nvm install v12.12.0`
> 4. Use `Rosetta iTerm` to do `cdk deploy` commands

I gave this a try on my M1 Mac Mini and have yet to see a successful deployment, unfortunately.

Running:
- macOS 11.1
- iTerm via Rosetta
- Node v12.12.0
- AWS CDK v1.86.0

When clearing all cache folders, then executing a clean install, build, and deploy, I get the same empty zip warning and also log the following:

```
 ❌  MercuryApiStack failed: Error: The stack named [snip] failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/ckhicks/.nvm/versions/node/v12.12.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/Users/ckhicks/.nvm/versions/node/v12.12.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:283:26)
    at CdkToolkit.deploy (/Users/ckhicks/.nvm/versions/node/v12.12.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/Users/ckhicks/.nvm/versions/node/v12.12.0/lib/node_modules/aws-cdk/bin/cdk.ts:202:9)
The stack named MercuryApiStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

**Comment by cmckni3** [comment]
For now, I added a version resolution to my `package.json`. Yarn locked the offending version of node-archiver, `archiver`, even after downgrading AWS CDK.

package.json:

```
  "resolutions": {
    "archiver": "~5.1.0"
  }
```

**Comment by cmckni3** [comment]
> For now, I added a version resolution to my `package.json`. Yarn locked the offending version of node-archiver, `archiver`, even after downgrading AWS CDK.
> 
> package.json:
> 
> ```
>   "resolutions": {
>     "archiver": "~5.1.0"
>   }
> ```

Worked after clearing `cdk.out` and S3 bucket.

**Comment by ckhicks** [comment]
@cmckni3 Glad you got it working - I just tried each of those steps after downgrading to CDK `1.74.0` and still get the same errors. :/

**Comment by cmckni3** [comment]
> @cmckni3 Glad you got it working - I just tried each of those steps after downgrading to CDK `1.74.0` and still get the same errors. :/

I kept CDK at 1.86.0. Make sure you run an install after update `package.json`.

**Comment by ckhicks** [comment]
> > @cmckni3 Glad you got it working - I just tried each of those steps after downgrading to CDK `1.74.0` and still get the same errors. :/
> 
> I kept CDK at 1.86.0. Make sure you run an install after updating `package.json`.

Still no dice on my M1 Mac - thanks though! I'll keep at it. ⛏️

**Comment by scubbo** [comment]
I have downgraded all `aws-cdk` packages to `1.74.0`, set `archiver` to `~5.1.0` as cmckni3 suggested, deleted uploaded s3 files, run `rm -rf cdk.out/*`, and run `npm install` - and I'm still getting this same issue (confirmed that the uploaded files _are_ non-empty).

**Comment by ebh** [comment]
@scubbo, are you using a docker container? I was running `cdk` in the `node:latest` container and had to, in addition to setting `archiver` to `~5.1.0` & deleting all objects in the S3 bucket, switch to using `node:lts`.

**Comment by scubbo** [comment]
Nope, no docker container. I just tried creating a fresh project in case I had some weird configuration leftover, and it's still erroring:

```
$ git init testProject
Initialized empty Git repository in /Users/scubbo/Code/testProject/.git/
$ cd testProject
$ cdk init app --language typescript
...
$ rm package-lock.json
####
# ...in IDE, edit package.json and create rudimentary app, then...
####
$ cat package.json
{
  "name": "test_project",
  "version": "0.1.0",
  "bin": {
    "test_project": "bin/test_project.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "1.74.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "1.74.0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/core": "1.74.0",
    "@aws-cdk/aws-lambda": "1.74.0",
    "source-map-support": "^0.5.16"
  },
  "resolutions": {
    "archiver": "~5.1.0"
  }
}
$ cat lambda/index.py
def handler(event, context):
  print('hello world')
$ cat lib/test_project-stack.ts
import * as cdk from '@aws-cdk/core';
import {AssetCode, Function, Runtime} from '@aws-cdk/aws-lambda';

export class TestProjectStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const backend = new Function(this, 'backend-lambda', {
      code: new AssetCode("lambda/"),
      handler: "index.handler",
      runtime: Runtime.PYTHON_3_8
    })

  }
}
$ aws s3 ls s3://cdktoolkit-stagingbucket-<id>/assets/
[no contents]
$ touch .npmignore && rm -rf node_modules  # to avoid an "ENOENT" error
$ npm install
[...]
$ cdk deploy
[Same "Uploaded file must be a non-empty zip" error]
$ aws s3 ls s3://cdktoolkit-stagingbucket-<id>/assets/
2021-01-25 22:55:03        184 83674[...].zip
$ aws s3 cp s3://cdktoolkit-stagingbucket-<id>/assets/83674[...].zip /tmp/zipfile.zip
$ unzip -l /tmp/zipfile.zip
Archive:  /tmp/zipfile.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-01-1980 00:00   index.py
---------                     -------
        0                     1 file
$ unzip /tmp/zipfile.zip
Archive:  /tmp/zipfile.zip
  inflating: index.py                 bad CRC 5c545933  (should be 00000000)
$ cat index.py
def handler(event, context):
  print('hello world')
```

**Comment by nija-at** [comment]
I was able to reproduce this using Node v15.6 and was absent in Node v15.5 and lower. 
Until we investigate further and find a different resolution, please use node engine < 15.6.0

**Comment by nija-at** [comment]
I am able to confirm that downgrading archiver from 5.2.0 to 5.1.0 does not resolve this problem. This seems tied to the node release 15.6.0.

**Comment by christophgysin** [comment]
@nija-at Just in case you missed it, the root cause is https://github.com/nodejs/node/issues/37027.

And a small nit regarding the changed title: The generated zip files are not actually empty, just corrupt (bad CRC). It's simply the error message displayed by CDK that reads "Uploaded Zips of Functions are Empty".

**Comment by gibbster** [comment]
I tried downgrading node and am still facing this issue:
`node --version
v15.5.1`

I also cleared out the CDK staging bucket, and `rm -rf node_modules package-lock.json && npm i` before redeploying.

FWIW, here's the dependencies I have in my package.json:

```
  "devDependencies": {
    "@aws-cdk/assert": "1.86.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "1.86.0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/aws-apigateway": "^1.86.0",
    "@aws-cdk/aws-batch": "^1.86.0",
    "@aws-cdk/aws-cloudfront": "1.86.0",
    "@aws-cdk/aws-cloudfront-origins": "1.86.0",
    "@aws-cdk/aws-cognito": "^1.86.0",
    "@aws-cdk/aws-dynamodb": "^1.86.0",
    "@aws-cdk/aws-ec2": "^1.86.0",
    "@aws-cdk/aws-ecr": "^1.86.0",
    "@aws-cdk/aws-ecs": "^1.86.0",
    "@aws-cdk/aws-events": "^1.86.0",
    "@aws-cdk/aws-events-targets": "^1.86.0",
    "@aws-cdk/aws-lambda": "^1.86.0",
    "@aws-cdk/aws-lambda-nodejs": "^1.86.0",
    "@aws-cdk/aws-rds": "^1.86.0",
    "@aws-cdk/core": "1.86.0",
    "source-map-support": "^0.5.16"
  },
  "resolutions": {
    "archiver": "~5.1.0"
  }
```

**Comment by nija-at** [comment]
@gibbster - you also need to delete the `cdk.out` folder. The asset is cached in there.

**Comment by nija-at** [comment]
@christophgysin - thanks for pointing this out. I've adjusted the title.

**Comment by christophgysin** [comment]
@gibbster I think I also needed to delete the asset in the S3 staging bucket. IIRC the hash is calculated over the inputs, not the resulting zip. So the corrupt zip and the valid zip might have the same hash!

**Comment by gibbster** [comment]
Thanks @christophgysin and @nija-at - clearing the `cdk.out` folder did the trick!

**Comment by scubbo** [comment]
I can confirm that, after downgrading my Node version to 15.5.1 (for any other Node newbies who were confused about how to do this, it doesn't seem to be possible via `brew install node@15.5.1` - I had to use [n](https://stackoverflow.com/a/50287454/1040915) on my Mac), my deploy succeeds with `1.86.0` CDK dependencies (no need for `1.74.0`), and without a pinned `archiver` version.

**Comment by alex-hladun** [comment]
Still getting error with Node 15.5 and clearing bucket (using CircleCI so no cdk.out).

**Comment by alst-monosolutions** [comment]
Experiencing the issue with Node 10.17, CDK 1.74 as well 1.78

**Comment by machielg** [comment]
I think the main culprit is archive.js version 5.2.0. @nija-at would it be possible for the CDK cli to pin the version of archive js to 5.1.0 until the bug has been solved?

**Comment by vinnayb29** [comment]
I have tried node 15.6.0, 15.5.0. Cleared cdk.out still facing the issue

**Comment by nija-at** [comment]
@machielg - Last I checked, the combination of Node15.6+archiverjs-5.1.0 still manifested the bug.

**Comment by jorgeprz10** [comment]
tried node 14 with 1.87 while clearing out the cdk.out/cache. It worked... the first time with a brand new bootstrap. afterwards it fails regardless of emptying the staging bucket and cdk.out.

**Comment by shaftoe** [comment]
I've not been able to fix it even following the above suggestions of downgrading both `Node.js` and `cdk`. 

My downgraded env:

- macOS `10.15.7`, Node.js `14.15.4` installed via `homebrew`
- cdk version `1.79.0` installed via `npm` + tarball following [official instructions](https://github.com/aws/aws-cdk/blob/master/MANUAL_INSTALLATION.md)

I could also reproduce the bug with all packages up to date, i.e. Node.js `15.7.0` and CDK `1.87.1 (build 9eeaa93)`

**Comment by Tantalon** [comment]
There's three things needed to work around it:
* Downgrade node to 15.5 or earlier
* Delete your cdk.out directory
* Empty your cdk staging S3 bucket

**Comment by lekkerdriveway** [comment]
+1 to this. I was having this same issue. Was able to resolve with downgrade of node to v14.15.4, delete cdk.out and empty the cdk staging bucket. I kept aws-cdk version 1.87.1 (build 9eeaa93) didn't seem to cause a problem.

**Comment by fabriciolelis** [comment]
I use **node versions 14.15.4 and 15.7.0** with **CDK versions 1.87.1 and 1.74.0** 
I deleted cdk.out, the files on the bucket
And the problem persists.

**Comment by JBirdVegas** [comment]
I'm unable to get the _fix_ to work

```
% npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm
% rm -rf cdk.out
% node --version
v14.15.4
% cdk --version
1.87.1 (build 9eeaa93)
% cdk deploy
...
Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 84803229-94d2-4273-8b12-4a4b647cc4d4; Proxy: n
ull)
...
```

**Comment by machielg** [comment]
anyone know how to downgrade the archive.js  package in the aws cdk installation?

**Comment by cmckni3** [comment]
Problem has returned for me on node.js 12.20.0, AWS CDK 1.86.0, and node-archiver 5.1.0.

I know the `AssetCode` and `Code` classes in CDK changed recently 🤔.

**Comment by katrinabrock** [comment]
Tried fix/workaround in description, still not able to get it to work. Tried

- cdk version 1.81.0, node version 15.5.1
- cdk version 1.77.0, node version 14.15.4

Each time deleted cdk.out and `s3://cdktoolkit-stagingbucket-XXXXX/assets`. Also, removed leftover docker images like `for i in `docker image list|awk '{print $1}'|grep cdk`; do docker image rm $i; done` for good measure. 

I'm on OS X 10.15.7.

I haven't attempted modifying archiver version independently.

**Comment by machielg** [comment]
> Problem has returned for me on node.js 12.20.0, AWS CDK 1.86.0, and node-archiver 5.1.0.
> 
> I know the `AssetCode` and `Code` classes in CDK changed recently. 🤔

I also remember seeing some `await` statements being removed 🤔

**Comment by nija-at** [comment]
Interestingly, I've tried to reproduce this again and I'm only seeing this error for Node 15.6, while using the CDK 1.87.0.

I'll continue to see if there are other variables that might be causing this.

**Comment by cmckni3** [comment]
> Problem has returned for me on node.js 12.20.0, AWS CDK 1.86.0, and node-archiver 5.1.0.
> 
> I know the `AssetCode` and `Code` classes in CDK changed recently. 🤔

Issue occurred on CDK 1.74.0 again with node-archiver 5.1.0.

**Comment by NickTheSecurityDude** [comment]
I'm getting this same error using aws_s3_deployment

`Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: e9bf23f9-4fea-453f-aee7-4f2929
25506c; Proxy: null)`

My python code is:
`    deployment_.BucketDeployment(self,"Web Files",
      destination_bucket=bucket,
      sources=[deployment_.Source.asset(os.path.join(dirname, "files/web_files.zip"))]
    )
`
I'm using no de 15.7.0:
`% node -v
v15.7.0
`

**Comment by ckhicks** [comment]
Hit this again when doing a clean install - took me a minute to recall my original settings but these do work!

- macOS v11.1 (M1)
- iTerm v3.4.3 via Rosetta
- Node v12.12.0
- AWS CDK v1.86.0 (CLI & in `package.json` - make sure you remove the `^` operator!)
- Limit `archiver` to `5.1.0` in `package.json`

Long and frustrating, but it works. 😓

**Comment by cmckni3** [comment]
The problem keeps resurfacing for me. I upgraded `crc32-stream` to see if it helps.  🤞

**Comment by rsilvestre** [comment]
The same here with
- osx 11.1 (20C69)
- cdk 1.88.0 (build f65009b)
- node v15.8.0

**Comment by katrinabrock** [comment]
I tried running CDK in docker in hopes of iterating more quickly and finding reproducible working versions, but only ran into a different issue (https://github.com/aws/aws-cdk/issues/8799).

I've posted what I did so far here: https://github.com/katrinabrock/aws-cdk-dind-py-lambda .

**Comment by cmckni3** [comment]
> The problem keeps resurfacing for me. I upgraded `crc32-stream` to see if it helps. 🤞

Upgrading `crc32-stream` by specifying 4.0.2 in `resolutions` worked for me. No issues with AWS CDK 1.86.0 for 2 days.

**Comment by iliapolo** [comment]
Hi everyone, sharing my conclusions here as well:

- Working: `crc32-stream` **>=** `4.0.2` **OR** Node **<=** `15.5.0`
- Non working: `crc32-stream` **<** `4.0.2` **AND** Node **>** `15.5.0`

I know some folks have been reporting conflicting results, before we dive deeper into that, I wanted to clarify something about the subtleties of asset caches. It might explain some of this behavior. 

Note that its not sufficient to remove only the asset your code is creating, but also the assets created by the framework.

For example, the `BucketDeployment` constructs bundled its own asset, that contains the lambda code, inside the `cdk.out` directory. If you used a faulty combination and deployed the stack, the lambda code asset itself will be corrupted, and any subsequent deployment will suffer from the same problem, regardless of if you removed your own asset. To address this, you need to delete all assets that are included in your stack:

```bash
staging_bucket=$(aws cloudformation describe-stack-resources --stack-name CDKToolkit --logical-resource-id StagingBucket --query 'StackResources[].PhysicalResourceId' --output=text)
for asset in $(ls cdk.out | grep asset); do
  hash=$(echo ${asset} | cut -d'.' -f2)
  aws s3 rm s3://${staging_bucket}/assets/${hash}.zip
done
```  

It's also a good idea to just nuke the entire `cdk.out` directory instead of specific assets inside it.

I've created this [reproduction repo](https://github.com/iliapolo/aws-cdk-issue12536) that does all that for you and also allows specifying different versions of the relevant components. You can use it for sanity checks as well as plugging in your own stack.

**Comment by shaftoe** [comment]
@iliapolo thanks a lot for taking the time for making it _sharable_, I can confirm it did the trick for me, i.e.:

1. run the above shell script
2. rimraffed `cdk.out`
3. downgraded Node to v14 via Homebrew
4. `cdk deploy`

**Comment by katrinabrock** [comment]
Some heroes wear capes. Some heroes wear whatever this is:
![img](https://avatars.githubusercontent.com/u/1428812?s=150&v=4)

Working now! ❤️ 

I'm using python flavor of CDK, I had to remove this line from @iliapolo 's  run.sh https://github.com/iliapolo/aws-cdk-issue12536/blob/main/run.sh#L72 

packages.json is this:
```
{
  "dependencies": {
    "aws-cdk": "1.88.0",
    "yarn": "^1.22.10"
  },
  "resolutions": {
    "archiver": "5.2.0",
    "crc32-stream": "4.0.2"
  }
}
```
Of course, I also had to make sure the version of the python aws-cdk.* packages matches cdk version (`1.88.0` if you use run.sh script as-is). I'm also still clearing out leftover docker images that CDK generates. Not sure if that is needed or not.

**Comment by cmckni3** [comment]
> Hi everyone, sharing my conclusions here as well:
> 
> * Working: `crc32-stream` **>=** `4.0.2` **OR** Node **<=** `15.5.0`
> * Non working: `crc32-stream` **<** `4.0.2` **AND** Node **>** `15.5.0`
> 
> I know some folks have been reporting conflicting results, before we dive deeper into that, I wanted to clarify something about the subtleties of asset caches. It might explain some of this behavior.
> 
> Note that its not sufficient to remove only the asset your code is creating, but also the assets created by the framework.
> 
> For example, the `BucketDeployment` construct bundles its own asset (that contains the lambda code) inside the `cdk.out` directory. If you used a faulty combination and deployed the stack, the lambda code asset itself will be corrupted, and any subsequent deployment will suffer from the same problem, regardless of if you removed your own asset. To address this, you need to delete all assets that are included in your stack:
> 
> ```shell
> staging_bucket=$(aws cloudformation describe-stack-resources --stack-name CDKToolkit --logical-resource-id StagingBucket --query 'StackResources[].PhysicalResourceId' --output=text)
> for asset in $(ls cdk.out | grep asset); do
>   hash=$(echo ${asset} | cut -d'.' -f2)
>   aws s3 rm s3://${staging_bucket}/assets/${hash}.zip
> done
> ```
> 
> It's also a good idea to just nuke the entire `cdk.out` directory instead of specific assets inside it.
> 
> I've created this [reproduction repo](https://github.com/iliapolo/aws-cdk-issue12536) that does all that for you and also allows specifying different versions of the relevant components. You can use it for sanity checks as well as plugging in your own stack.

Yeah, I mentioned the crc32-stream piece previously. I went through the archiver GitHub issue to find the crc32-stream bug and release fix. Maybe I wasn’t clear in my multiple comments but the fix was tough to validate. 1-2 deploys would work then a deploy would fail.

FYI, this wasn’t limited to node 15.x. I always had issues with node 12.x. Still not sure why folks use the odd (non-LTS) versions of node.

**Comment by jpaas** [comment]
crc32-stream 4.0.2 fixed it for me with node 15.7.0. Thanks @cmckni3 and @katrinabrock !

**Comment by shaftoe** [comment]
> Still not sure why folks use the odd (non-LTS) versions of node.

@cmckni3 In general I'd expect developers to prefer the advertised "Current" version (new features, hopefully less bugs, etc). Also, on macOS when installing with Homebrew (`brew install node`) you get the latest Node.js version. LTS option seems to be more appealing for system administrators, where stability comes before feature richness, etc.

**Comment by shaftoe** [comment]
By the way upgrading to CDK version `1.89.0 (build df7253c)` and Node.js `v15.8.0` + running https://github.com/iliapolo/aws-cdk-issue12536 helper doesn't work for me, still hitting the `Uploaded file must be a non-empty zip` error.

Downgrading Node.js to `v14.15.5` while keeping `1.89.0 (build df7253c)` and removing `cdk.out` and remote assets works though.

**Comment by iliapolo** [comment]
The fix will be available in the next release.

**Comment by iliapolo** [comment]
@shaftoe Did you run the `run.sh` as is? with `crc32-stream` at version `4.0.2`?

**Comment by shaftoe** [comment]
@iliapolo not as is, just the part that removes local and remote assets:

```bash
staging_bucket=$(aws cloudformation describe-stack-resources --stack-name CDKToolkit --logical-resource-id StagingBucket --query 'StackResources[].PhysicalResourceId' --output=text)
for asset in $(ls cdk.out | grep asset); do
  hash=$(echo ${asset} | cut -d'.' -f2)
  aws s3 rm s3://${staging_bucket}/assets/${hash}.zip
done
rm -rf cdk.out
```

 I thought I checked and saw that `crc32-stream` version was `4.0.2` but I might be wrong, I installed again v15 + reinstalled cdk to double check and I see it's still `4.0.1`.

**Comment by iliapolo** [comment]
Yeap. So if you install the CLI using npm, you'll get `4.0.1` because we actually lock our dependencies with a `shrinkwrap` file. If you use `yarn` though, you'll get `4.0.2` because it doesn't respect shrinkwrap files.

**Comment by shaftoe** [comment]
Understood, thanks for the explanation 👍

**Comment by kokachev** [comment]
Below is the version of the script for anyone using newStyleSynthesis and cdk>=1.89.0:
`
staging_bucket=$(aws cloudformation describe-stack-resources --stack-name CDKToolkit --logical-resource-id StagingBucket --query 'StackResources[].PhysicalResourceId' --output=text)
for asset in $(ls cdk.out | grep -e "^asset"); do
  hash=$(echo ${asset} | cut -d'.' -f2)
  aws s3 rm s3://${staging_bucket}/${hash}.zip
done
rm -rf cdk.out
`

**Comment by rpawlaszek** [comment]
Similar issue with BucketDeployment.

I'm using node 15.8.0:
`% node -v v15.8.0`

CDK 1.89.0:
`% cdk --version 1.89.0 (build df7253c)`

**Comment by katrinabrock** [comment]
@iliapolo 's solution is working for me on OS X. 

I'm attempting to run CDK in docker (`ubuntu:18.04`), and I still can't seem to avoid this issue.

Here's the code I'm using: https://github.com/katrinabrock/aws-cdk-dind-py-lambda

Anyone who got this working on linux, what distro/version are you using?

**Comment by RicoToothless** [comment]
> @iliapolo 's solution is working for me on OS X.
> 
> I'm attempting to run CDK in docker (`ubuntu:18.04`), and I still can't seem to avoid this issue.
> 
> Here's the code I'm using: https://github.com/katrinabrock/aws-cdk-dind-py-lambda
> 
> Anyone who got this working on linux, what distro/version are you using?

someone share his experience
https://github.com/aws/aws-cdk/issues/12536#issuecomment-765439298

**Comment by amaheshwari21** [comment]
This issue seems to be fixed on latest version of node. I have tested this with node 15.12.0 "node -v -- v15.12.0". It is working so far for me.

**Comment by zxkane** [comment]
I met the error `Could not unzip uploaded file. Please check your file, then try to upload again.` for updating a Lambda layer after bumping CDK from `1.91.0` to `1.95.1`. The node version is `v12.21.0`. 

Looks like the fix still has problem in case updating the existing stack. The stack updating succeeded after using above script to clean all assets in `cdktoolkit` bucket.

**Comment by hugomallet** [comment]
Same issue on Mac 11.2.3 with Node 15.14.0 and cdk 1.97.0

Sometimes I have another error : 
Error: ENOENT: no such file or directory, open 'node_modules/.bin/semver'

**Comment by bgshacklett** [comment]
My currently working configuration is Node v14.16.1 (LTS) and CDK version 1.100.0.

As others have stated, clearing the staging bucket of affected assets is required to fix this problem. After becoming aware of this issue, running `cdk deploy ... -vvv` indicated that CDK was detecting a pre-existing asset within the staging bucket. With this asset already uploaded, CDK skipped uploading the current copy (leaving a corrupted zip file in place) and proceeded to attempt to use the corrupted zip file in the following Lambda function deployment.

My issue was resolved after updating to the previously mentioned Node and CDK versions, then removing the assets which were indicated in the verbose output produced by the `-vvv` flag.

**Comment by SamuelCabralCruz** [comment]
Encountered the present issue in the past and dev team's response did work, but now I faced the problem again following update of aws-cdk from 1.113.0 to 1.114.0 with node 14.17.3. After downgrading aws-cdk back to 1.113.0 and cleaning the staging bucket, everything worked fine again.

Hope you guys will find a real fix soon. 🙏

**Comment by amirfireeye** [comment]
This ugly script fixes assets after deploy so you can deploy again. Run it in the root folder of your project so it can find `cdk.out`. It iterates over assets listed in `manifest.json`, downloads them from S3, extracts to a temporary folder, re-zips, and finally uploads back to S3.

```
#!/bin/bash
set -ex

ASSEMBLY_DIRECTORY=`jq -r '.artifacts[] | select(.type == "cdk:cloud-assembly") | .properties.directoryName' cdk.out/manifest.json`
ASSET_MANIFESTS=`jq -r '.artifacts[] | select(.type == "cdk:asset-manifest") | .properties.file' cdk.out/$ASSEMBLY_DIRECTORY/manifest.json`
cd cdk.out/$ASSEMBLY_DIRECTORY
ASSETS=`jq -r '.files[].destinations[] | "s3://" + .bucketName + "/" + .objectKey' $ASSET_MANIFESTS | grep zip`

TMP=`mktemp -d`
cd $TMP

for ASSET in $ASSETS
do
    if aws s3 ls $ASSET; then
        aws s3 cp $ASSET pkg.zip
        mkdir s
        cd s
        if ! unzip ../pkg.zip; then echo bad zip; fi
        rm ../pkg.zip
        zip -r ../pkg.zip * .gitempty
        aws s3 cp ../pkg.zip $ASSET
        cd ..
        rm -rf s
    fi
done

rm -rf $TMP
```

**Comment by timmattison** [comment]
I'm seeing this in 1.121.0 today.

**Comment by bgshacklett** [comment]
@timmattison does anyone else perform deployments who might be using an older version? Are you able to replicate after clearing out the affected assets from the bucket? Is it possible for you to share the log output using the `-vvv` flag?

**Comment by robertd** [comment]
@timmattison can you share you package.json and package-lock.json files?

**Comment by timmattison** [comment]
Of course I fixed this before I went on vacation and now I don't remember what I changed. It was an error on my end but the error message didn't help me diagnose what was wrong. I'll take a look and see what I can find and report back either way.

**Comment by timmattison** [comment]
I can't find it now. I want to say that this was an issue where there was a require that was referencing a file that didn't exist but in CDK 122 it seems to throw an error early saying that the module couldn't be found. If I ever figure it out I'll post it here but for now I think we will have to ignore it without reproduction steps. :-/

**Comment by SamuelCabralCruz** [comment]
just tried with node 16.13.0 and cdk 132 and everything seems fine! thx yall!

**Comment by rtatton** [comment]
For future reference, I'm adding my experience with this issue.

**Configuration**
- CDK: 1.152.0
- CDK CLI: 2.20.0 (build 738ef49)
- Node: 12.22.12
- npm: 6.14.16
- Gradle: Gradle 7.4.2
- Java: 11
- OS: Mac OS X 12.3.1 aarch64

I had a Gradle project for each Lambda handler and a Gradle project for CDK code, i.e.,
```
root
|
--- cdk-code
|
---
    |
    --- cdk.json
    --- cdk.out
|
--- lambda-handler-1
|
--- lambda-handler-2
|
.
.
.
--- gradlew
``` 
Each Lambda handler project used the Java application Gradle plugin, so when bundling locally, I had to use
```
../gradlew clean check distZip
```
since `BundlingOutput.ARCHIVED` requires exactly one archive file in the directory (i.e., no `.tar` archive). Really, only the `distZip` is necessary, but cleaning and running checks is a safe option.

So what I would try to run is `cdk bootstrap`, then `cdk synth`, and then `cdk deploy`. Bootstrapping and synthesizing would complete successfully, and I could verify that all handler ZIP archives were properly being picked up by CDK and hashed (using `AssetHashType.OUTPUT`) to `cdk.out`. However, when I would run `cdk deploy`, I noticed that an empty ZIP file would appear in `cdk.out`.

The key observation that ultimately helped me was the following. Upon running `cdk synth`, I confirmed that each handler `aws:asset:path` matched what was in `cdk.out`. However, upon running `cdk deploy`, the value of `aws:asset:path` (located under "Metadata")  for all handlers changed to the hash of the empty ZIP archive. From what I could tell, it's as if CDK didn't recognize that the handlers were already bundled, and so `cdk deploy` "bundled the bundled assets."

To fix the issue, I simply deleted `cdk.out` after running `cdk synth` and then ran `cdk deploy`. I haven't confirmed, but I think running `cdk synth --no-staging` would save you the trouble of deleting `cdk.out`.

This is only the second project I have worked with CDK, so I may be missing some critical detail about how to properly use CDK or the CDK CLI that would've avoided this issue, but it didn't seem to be caused by any partcular version of software I was using.
