### ISSUE TITLE
aws-ecs: Can't create UDP-only container

### ISSUE THREAD

**Issue by bkeifer** [aws/aws-cdk#20887]
### Describe the bug

Creating a container with only UDP port mappings produces the following error when synthing:

Container 'AuthDNSApplicationStack/TaskDefUDP/ContainerUDP' has no mapping for port undefined and protocol tcp. Did you call "container.addPortMappings()"?

### Expected Behavior

Start a container which handles requests to the NLB on 53/udp

### Current Behavior

Error message:

`Container 'AuthDNSApplicationStack/TaskDefUDP/ContainerUDP' has no mapping for port undefined and protocol tcp. Did you call "container.addPortMappings()"?`

### Reproduction Steps

```
this.loadBalancer = new NetworkLoadBalancer(this, 'dnsLB', {
    vpc: assets.vpc,
    internetFacing: true,
    crossZoneEnabled: true,
    vpcSubnets: {
        subnets: assets.myCorpNetworkResources.getSubnets(assets.networkEnvironment, SubnetType.PUBLIC),
    },
});
this.cfnNLB = this.loadBalancer.node.defaultChild as CfnLoadBalancer;

const subnetMapping1: CfnLoadBalancer.SubnetMappingProperty = {
    subnetId: assets.myCorpNetworkResources.getSubnets(assets.networkEnvironment, SubnetType.PUBLIC)[0].subnetId,
    allocationId: assets.elasticIp1.attrAllocationId,
}
const subnetMapping2: CfnLoadBalancer.SubnetMappingProperty = {
    subnetId: assets.myCorpNetworkResources.getSubnets(assets.networkEnvironment, SubnetType.PUBLIC)[1].subnetId,
    allocationId: assets.elasticIp2.attrAllocationId,
}
this.cfnNLB.addDeletionOverride('Properties.Subnets');
this.cfnNLB.subnetMappings = [subnetMapping1, subnetMapping2];


const targetGroup = new NetworkTargetGroup(this, 'TargetGroup', {
    vpc: assets.vpc,
    port: 53,
    protocol: Protocol.UDP,
    targetType: TargetType.IP,
    deregistrationDelay: Duration.seconds(10),
});
  

const listener = this.loadBalancer.addListener('Listener', {
    port: 53,
    protocol: Protocol.UDP,
});

listener.addTargetGroups('TargetGroup', targetGroup);


const taskDefDefaults = {
    compatibility: Compatibility.FARGATE,
    cpu: '256',
    memoryMiB: '512',
}
const taskDefUDP = new TaskDefinition(this, 'TaskDefUDP', taskDefDefaults);

  
const containerUDP = taskDefUDP.addContainer('ContainerUDP', {
    image: ContainerImage.fromEcrRepository(repository),
    environment: {
        "AWS_ENVIRONMENT": awsEnvironmentString,
        "SLACK_WEBHOOK": assets.slackWebhook,
    },
    logging: LogDrivers.awsLogs({
        logGroup: assets.dnsLogGroup,
        streamPrefix: 'dns',
    })
});
containerUDP.addPortMappings({
    containerPort: 53, 
    hostPort: 53, 
    protocol: ecs.Protocol.UDP
});
```

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v14.16.1

### OS

MacOS 12.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
I can't reproduce this with the code snippet you've provided on the latest version, either this has been fixed or you may need to provide a different code snippet which can guarantee this error throws

**Comment by ssko1** [comment]
Hi, I was able to reproduce the issue with the following code on `2.43.0 (build 487870a)`, building on AmazonLinux2. I believe this is an issue when the target group tries to validate that an ECS Service container has the ports required.

```typescript
const vpc = ...

const containerImage = ...

const cluster = new Cluster(this, 'Cluster', {})

const taskDefinition = new TaskDefinition(this, 'TaskDefinition', {
    compatibility: Compatibility.EC2,
})

const container = taskDefinition.addContainer('Container', {
    image: containerImage,
    cpu: 1024,
    memoryLimitMiB: 1024,
})

container.addPortMappings({
    containerPort: 2003,
    hostPort: 2003,
    protocol: aws_ecs.Protocol.UDP,
})

const service = new Ec2Service(this, 'Service', {
    cluster: cluster, taskDefinition: taskDefinition
})

const nlb = new NetworkLoadBalancer(this, 'Nlb', {
    vpc: vpc,
})

const listener = nlb.addListener('Listener', {
    protocol: Protocol.UDP,
    port: 2003,
})

listener.addTargets('TargetGroup', { // throws error
    port: 2003,
    protocol: Protocol.UDP,
    targets: [service]
})
```

Error Message
```
Error: Container '[...]/TaskDefinition/Container' has no mapping for port undefined and protocol tcp. Did you call "container.addPortMappings()"?
```

**Comment by Gillies** [comment]
> Hi, I was able to reproduce the issue with the following code on `2.43.0 (build 487870a)`, building on AmazonLinux2. I believe this is an issue when the target group tries to validate that an ECS Service container has the ports required.
> 
> ```ts
> const vpc = ...
> 
> const containerImage = ...
> 
> const cluster = new Cluster(this, 'Cluster', {})
> 
> const taskDefinition = new TaskDefinition(this, 'TaskDefinition', {
>     compatibility: Compatibility.EC2,
> })
> 
> const container = taskDefinition.addContainer('Container', {
>     image: containerImage,
>     cpu: 1024,
>     memoryLimitMiB: 1024,
> })
> 
> container.addPortMappings({
>     containerPort: 2003,
>     hostPort: 2003,
>     protocol: aws_ecs.Protocol.UDP,
> })
> 
> const service = new Ec2Service(this, 'Service', {
>     cluster: cluster, taskDefinition: taskDefinition
> })
> 
> const nlb = new NetworkLoadBalancer(this, 'Nlb', {
>     vpc: vpc,
> })
> 
> const listener = nlb.addListener('Listener', {
>     protocol: Protocol.UDP,
>     port: 2003,
> })
> 
> listener.addTargets('TargetGroup', { // throws error
>     port: 2003,
>     protocol: Protocol.UDP,
>     targets: [service]
> })
> ```
> 
> Error Message
> 
> ```
> Error: Container '[...]/TaskDefinition/Container' has no mapping for port undefined and protocol tcp. Did you call "container.addPortMappings()"?
> ```

I know this is kind of delayed but hopefully it will help someone else stumbling on this, but I ran in to the same issue with this and found the solution was instead of passing the service as the target, I passed it the return value from ```service.loadBalancerTarget()``` along with updating my container to have a containerName in the props

**Comment by bkeifer** [comment]
> I know this is kind of delayed but hopefully it will help someone else stumbling on this, but I ran in to the same issue with this and found the solution was instead of passing the service as the target, I passed it the return value from `service.loadBalancerTarget()` along with updating my container to have a containerName in the props

Would you, by any chance, be able to provide your working code?  I'm still not having any luck here.

**Comment by ssko1** [comment]
@bkeifer 
```typescript
const lbTarget = ec2Service.loadBalancerTarget({
  containerPort: 8080,
  protocol: Protocol.UDP,
  containerName: 'Container',
});

targetGroup.addTarget(lbTarget);
```
