### ISSUE TITLE
cdk deploy: [Error at /StackName] Request limit exceeded

### ISSUE THREAD

**Issue by farfaro** [aws/aws-cdk#21761]
### Describe the bug

We have problems when we run deploy (this stack contains a ECS):
![image](https://user-images.githubusercontent.com/41585747/186729423-e3b970d4-7829-475a-aa18-3133b72546ef.png)

Meanwhile, we also have this other stack, This contains several stacks of lambdas. But in this case it fails in the cdk synth:
![image](https://user-images.githubusercontent.com/41585747/186729948-034d4675-dd13-462a-9ad9-a50cdb5d6284.png)

In this last case, we use this image "amazon/aws-sam-cli-build-image-nodejs14.x:latest" + typescript@4.7.4 + aws-cdk@2.38.1  in GitLab SaaS

The message are the same:
"Request limit exceeded"
This happens with new commits, and with old commits.

### Expected Behavior

Update existing Stacks.

### Current Behavior

[Error at /My-LambdaStack] Request limit exceeded.

### Reproduction Steps

Just run "cdk deploy" and try to update/create a Lambda stack.
The region is us-east-1 (N. Virginia)

### CDK CLI Version

aws-cdk@2.38.1

### Node.js Version

nodejs14

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (4.7.4)

**Comment by jsonpj3wt** [comment]
I have also seen this and in our scenario, I limited the number of stacks being constructed to 3 (3 base stacks) and each call `ec2.Vpc.fromLookup(...)`.  This wasn't a problem yesterday but it does look like something is up because why would calling a lookup 3 times hit any type of request limit?

**Comment by farfaro** [comment]
It would seem that I no longer have this error. Are you the same?
@jsonpj3wt 
@m00ki3 


@madeline-k  do you know if there are errors with the AWS API?

**Comment by jsonpj3wt** [comment]
@farfaro I am also seeing it stabilize.  

@madeline-k can we get any kind of status to work with and inform our clients on deployments?

**Comment by m00ki3** [comment]
hmm, seems to be stabilizing...HOWEVER, I was lured into that false sense of security earlier when it was intermittent. So, I'd like to hear something from AWS to KNOW this is fixed.

**Comment by m00ki3** [comment]
I'm not seeing the issue on any of my pipelines any longer.

**Comment by TheRealAmazonKendra** [comment]
You should no longer be seeing this issue. Customers should AWS Health Dashboard for more information.

**Comment by farfaro** [comment]
@TheRealAmazonKendra 
It's the first thing I did. The board showed the healthy services, however the error was still reproduced.

**Comment by peterwoodworth** [comment]
There's not enough information to investigate with here. However it sounds like this has mostly been resolved. If you still run into this, please create a new issue. Thanks!
