### ISSUE TITLE
What happened to Amazon.CDK.AWS.Apigatewayv2.Integrations.HttpAlbIntegration?

### ISSUE THREAD

**Issue by icelava** [aws/aws-cdk#28255]
### Describe the bug

https://github.com/aws/aws-cdk/releases/tag/v2.112.0

Looks like 2.112.0 finally make Amazon.CDK.AWS.Apigatewayv2 official.

On dropping the alpha libraries from Visual Studio, appears the entire Amazon.CDK.AWS.Apigatewayv2.Integrations namespace is missing and HttpAlbIntegration cannot be found.

### Expected Behavior

HttpAlbIntegration still available. This is what we use to integrate HTTP API to our backend ALB.

### Current Behavior

HttpAlbIntegration missing from Amazon.CDK.Lib.

### Reproduction Steps

Update Amazon.CDK.Lib package to 2.113.0. Drop Amazon.CDK.AWS.Apigatewayv2.Alpha packages.

### Additional Information/Context

Looked through several pages of past alpha versions and didn't see anything breaking about HttpAlbIntegration.

### CDK CLI Version

2.111.0

### Framework Version

.NET 6.0

### Node.js Version

18.9.0

### OS

Windows 11

### Language

.NET

### Language Version

C# 10

### Other information

The independent Amazon.CDK.AWS.Apigatewayv2 packages available are for CDK 1.

**Comment by Dreamescaper** [comment]
Hopefully fixed in https://github.com/aws/aws-cdk/issues/28239.

**Comment by pahud** [comment]
Yes this could relate to https://github.com/aws/aws-cdk/pull/28250 and is expected be fixed in the next release.

I am closing this issue for now. Feel free to reopen if any concerns.

**Comment by icelava** [comment]
So apparently 2.114.0 is suppose to include the sub-modules and namespaces.

https://github.com/aws/aws-cdk/releases/tag/v2.114.0

But on downloading Amazon.CDK.Lib 2.114.1, the Amazon.CDK.AWS.Apigatewayv2.Integrations is still missing.
