### ISSUE TITLE
(aws-cdk-lib/aws-sqs): SQS queue using KMS key alias missing dependency

### ISSUE THREAD

**Issue by paulsukow** [aws/aws-cdk#28746]
### Describe the bug

SQS queues with a KMS key alias and downstream resources like S3 bucket notifications will fail creation. 

This does not happen when using the KMS key directly since the Queue will have a dependency on the key. For example:
```
"Queue600SFPD5": {
      "Properties": {
        "KmsMasterKeyId": {
          "Fn::GetAtt": [
            "QueueKey39DRBDQ9",
            "Arn",
...
```
Using the alias will result in a string for the KmsMasterKeyId and no dependency on the key creation or the alias creation:
```
"Queue600SFPD5": {
      "Properties": {
        "KmsMasterKeyId": {
          "Fn::Join": [
            "",
            [
              "arn:",
              {
                "Ref": "AWS::Partition",
              },
              ":kms:",
              {
                "Ref": "AWS::Region",
              },
              ":",
              {
                "Ref": "AWS::AccountId",
              },
              ":alias/keyAlias",
            ],
          ],
        },
....
```

### Expected Behavior

When using a KMS alias, the queue should depend on the alias.

### Current Behavior

In my example code, the bucket notification creations will fail with the error:
```Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations. See the details in CloudWatch Log Stream:...
```
Since that  resource's logic didn't wait for the key to be created.

### Reproduction Steps

Here is a sample stack that will fail:
```
import { Stack, StackProps } from 'aws-cdk-lib'
import { Alias, Key } from 'aws-cdk-lib/aws-kms'
import { Bucket, BucketEncryption } from 'aws-cdk-lib/aws-s3'
import { SqsDestination } from 'aws-cdk-lib/aws-s3-notifications'
import { Queue, QueueEncryption } from 'aws-cdk-lib/aws-sqs'
import { Construct } from 'constructs'

export class SampleStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props)

    const key = new Key(this, 'Key')
    const alias = new Alias(this, 'Alias', { aliasName: 'alias/keyAlias', targetKey: key })

    const queue = new Queue(this, 'Queue', {
      encryption: QueueEncryption.KMS,
      encryptionMasterKey: alias,
    })

    const bucket = new Bucket(this, 'Bucket', {
      encryption: BucketEncryption.KMS_MANAGED,
    })
    bucket.addObjectCreatedNotification(new SqsDestination(queue))
  }
}
```

### Possible Solution

My temporary solution in my stack is to add
`queue.node.addDependency(alias)`

### CDK CLI Version

2.121.1 (build d86bb1a)

### Node.js Version

20.x

### OS

OSX

### Language

TypeScript

### Language Version

5.3.3

**Comment by pahud** [comment]
I guess we should fix the dependency in the constructor.

**Comment by go-to-k** [comment]
@paulsukow 

You will solve this bug with the feature flag `KMS_ALIAS_NAME_REF` (`@aws-cdk/aws-kms:aliasNameRef`) on your cdk.json, see: https://github.com/aws/aws-cdk/pull/25822

**Comment by frankpengau** [comment]
I'm not sure if it's a similar issue but I'm having problems with getting my kms key set for the encryptionMasterKey under certain scenarios, aka separate class cdk construct. Will try and create a new repo to reproduce the error exactly as my internal company repo.

**Comment by paulsukow** [comment]
> @paulsukow
> 
> You will solve this bug with the feature flag `KMS_ALIAS_NAME_REF` (`@aws-cdk/aws-kms:aliasNameRef`) on your cdk.json, see: #25822

@go-to-k 
That does not solve this problem. The flag creates a implicit dependency between the KMS Alias and KMS Key. Here there needs to be a dependency between the Queue and the alias.

> This flag allows an implicit dependency to be created between KMS Alias and KMS Key when referencing key.aliasName or key.keyArn.

**Comment by go-to-k** [comment]
@paulsukow 

In my CDK code with the latest version, the CFn template will be the following:

```ts
const app = new cdk.App();

const stack = new cdk.Stack(app, 'sqs-bucket-notifications-test');

const key = new kms.Key(stack, 'Key');
const alias = new kms.Alias(stack, 'Alias', { aliasName: 'alias/keyAlias', targetKey: key });

const queue = new sqs.Queue(stack, 'Queue', {
  encryption: sqs.QueueEncryption.KMS,
  encryptionMasterKey: alias,
});

const bucket = new s3.Bucket(stack, 'Bucket', {
  encryption: s3.BucketEncryption.KMS_MANAGED,
});
bucket.addObjectCreatedNotification(new s3n.SqsDestination(queue));
```

```json
  "Alias325C5727": {
   "Type": "AWS::KMS::Alias",
   "Properties": {
    "AliasName": "alias/keyAlias",
    "TargetKeyId": {
     "Fn::GetAtt": [
      "Key961B73FD",
      "Arn"
     ]
    }
   }
  },
  "Queue4A7E3555": {
   "Type": "AWS::SQS::Queue",
   "Properties": {
    "KmsMasterKeyId": {
     "Fn::Join": [
      "",
      [
       "arn:",
       {
        "Ref": "AWS::Partition"
       },
       ":kms:",
       {
        "Ref": "AWS::Region"
       },
       ":",
       {
        "Ref": "AWS::AccountId"
       },
       ":",
       {
        "Ref": "Alias325C5727"
       }
      ]
     ]
    }
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete"
  },
```

Does this happen in your environment, in a new CDK PJ or an environment with feature flags turned on?

**Comment by paulsukow** [comment]
@go-to-k 
Generate the SQS Queue using a KMS Key and there will be an implicit dependency from the Queue on the Key. Using an KMS Alias is missing the dependency and uses a string instead

**Comment by go-to-k** [comment]
@paulsukow 

> This issue is between the SQS Queue and the KMS Alias,

In this CFn template, Queue depends on Alias, right? And of course alias depends on the key.

> Generate the SQS Queue using a KMS Key and there will be an implicit dependency from the Queue on the Key. Using an KMS Alias is missing the dependency and uses a string instead

In my (above) CDK code, using alias does not cause string dependencies.

Sorry if I am mistaken. I want to address this issue seriously.

```json
  "Queue4A7E3555": {
   "Type": "AWS::SQS::Queue",
   "Properties": {
    "KmsMasterKeyId": {
     "Fn::Join": [
      "",
      [
       "arn:",
       {
        "Ref": "AWS::Partition"
       },
       ":kms:",
       {
        "Ref": "AWS::Region"
       },
       ":",
       {
        "Ref": "AWS::AccountId"
       },
       ":",
       {
        "Ref": "Alias325C5727"
       }
      ]
     ]
    }
   },
```

**Comment by paulsukow** [comment]
Sorry I reread your code. I missed the `"Ref": "Alias325C5727"`

**Comment by paulsukow** [comment]
This is fixed with the flag. Sorry for the confusion @go-to-k

**Comment by paulsukow** [comment]
@go-to-k Thanks for the help!

Part of my confusion on your answer is that when I ran my snapshot test on my stack, the snapshot isn't being updated with the feature flag changes. When I run a full synth, the fix is there in the generated template. So I need to figure out why my tests are not updating with the flag changes

**Comment by paulsukow** [comment]
I guess this is to be expected behavior. Unit tests don't use the feature flags in cdk.json. https://github.com/aws/aws-cdk/issues/17553

@jfly Added a feature request for this in https://github.com/aws/aws-cdk/issues/18535 and states:
> I don't think this is a very sane default for users of cdk: I can totally see why people working on cdk would not want feature flags to automagically get enabled in tests, but IMO that's not appropriate behavior for users of cdk. 

I agree with his opinion that the CDK team may not want this feature, but that behavior is not good for users of CDK.  Users need to be able to trust that their unit tests reflect the actual state of what will be deployed.
