### ISSUE TITLE
cdk ls, synth, deploy commands hang in Linux

### ISSUE THREAD

**Issue by lohithsamaga** [aws/aws-cdk#5640]
cdk commands ls, synth and deploy hang in ubuntu 18.04. It works fine in Windows 10.

### Reproduction Steps

cdk init --language java
mvn clean package
cdk ls -lv > r

Will not display without redirect to file

### Error Log
CDK toolkit version: 1.19.0 (build 5597bbe)
Command line arguments: {
  _: [ 'deploy' ],
  v: true,
  verbose: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  ci: false,
  execute: true,
  '$0': '/usr/bin/cdk'
}
Determining whether we're on an EC2 instance.
Using proxy server: <https://proxy-server>
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true
}

Setting "CDK_DEFAULT_REGION" environment variable to <<region>>
Resolving default credentials
Does not look like EC2 instance.
Looking up default account ID from STS

### Environment

  - **CLI Version      :1.19.0**
  - **Framework Version: Node -> 12.13.1 npm -> 6.12.1**
  - **OS               : Ubuntu Desktop 18.04.3**
  - **Language         : Java**

### Other

--- 

This is :bug: Bug Report

**Comment by netroy** [comment]
@lohithsamaga this looks like you don't have the AWS CLI configured on that machine. 
But, since it's says `Does not look like EC2 instance`,  can I assume that this is a development machine?
If yes, you need to check 2 things:
1. run `aws configure` to create a default profile for all things AWS
2. check if AWS calls can go through the configured proxy server `https://proxy-server`

**Comment by lohithsamaga** [comment]
@netroy 

The credentials file in ~/,aws looks like below

[default]
aws_access_key_id=xxx
aws_secret_access_key=xxx
region=eu-west-1
[profile abcd-dev]
aws_access_key_id=xxx
aws_secret_access_key=xxx
region=eu-west-1


It works with proxy correctly.
Also, the "serverless" app works fine.

I have also set environment variables "CDK_DEFAULT_ACCOUNT" and "AWS_DEFAULT_ACCOUNT". But cdk still does not work

**Comment by netroy** [comment]
I haven't been able to reproduce this yet.
But, it looks like somehow the STS call to lookup your account-id is getting stuck.

are you able to get the account-id with `aws sts get-caller-identity` on the cli?
if you test this, please make sure that the aws cli is sending the calls through the proxy as well.

**Comment by shivlaks** [comment]
@lohithsamaga - spent some time trying to reproduce this issue today and I'm not running into it. I was testing with `1.22.0` - we did have a bug with proxy requests that was fixed in `1.21.0` but I believe it was introduced in `1.20.0` which would still be outside of the window of your issue.

It would be good to make the `aws sts get-caller-identity` call as @netroy suggested and verify it sends the call through. You should be able to verify that the call went through in CloudTrail if you have enabled it.

**Comment by lohithsamaga** [comment]
@netroy, @shivlaks 
Apologies for the delay.

You are right. It is getting stuck at the STS call.

aws sts get-caller-identity works fine with the proxy.

I have upgraded to version 1.22.0 and still face the same issue with cdk ls -l.

**Comment by keithlayne** [comment]
@lohithsamaga Are you by chance using Yarn 2 and/or PnP on your project?  If so, see #7839 for an issue that would potentially hang on linux but succeed on windows.

**Comment by shivlaks** [comment]
@lohithsamaga is this still an issue? trying to verify whether this issue is stale or still relevant
