### ISSUE TITLE
Convert from cfnParameter String to enum

### ISSUE THREAD

**Issue by riponbanik** [aws/aws-cdk#5742]
### The Question
Does not seem any way to convert String that is got from CfnParameter to enum like below which gives error -

# Encryption List
        ENCRYPTION_TYPES = [ "KMS", "KMS_MANAGED", "S3_MANAGED", "UNENCRYPTED"]
        
        encryption_param = core.CfnParameter(
                self,
                "Encryption",
                type="String",
                default="UNCRYPTED",
                allowed_values=ENCRYPTION_TYPES,
                dsecription="Encryption to use. Default None").value_as_string
        
        encryption_map = {
            "KMS": s3.BucketEncryption.KMS,
            "KMS_MANAGED": s3.BucketEncryption.KMS_MANAGED,
            "S3_MANAGED": s3.BucketEncryption.S3_MANAGED,
            "UNENCRYPTED": s3.BucketEncryption.UNENCRYPTED
        }
        
          bucketEnc = s3.Bucket(self, 
            "s3BucketEncrpted", 
             bucket_name = core.CfnParameter(self, "BucketNameEnc",type="String").value_as_string, 
             versioned=True,
             encryption=encryption_map[encryption_param])
 
### Environment

**CLI Version :** aws-cli/1.16.294
**Framework Version:** 1.19.0 (build 5597bbe)
**OS :** Linux/4.4.0-17763-Microsoft (WSL)
**Language :** Python

### Other information
Error is:
```console
  File "app.py", line 9, in <module>
    S3Stack(app, "s3")
  File "../build/s3/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "../build/s3/s3/s3_stack.py", line 52, in __init__
    encryption=encryption_map[encryption_param])
KeyError: '${Token[TOKEN.11]}'
```

**Comment by melchii** [comment]
Is it possible to pass the encryption type at build time when you generate the template? It seems like this wouldn't be possible because the CfnParameter is resolved at CloudFormation deploy time, not at build time.

Another approach if you're looking to maintain the CfnParameter is to convert your JavaScript encryption map to a CfnMapping. Then, at CloudFormation deploy time, CloudFormation can resolve the value and choose from the Mapping.

**Comment by john-kontralto** [comment]
I have this same issue. I would like to set the removal policy of a construct based on a `CfnParameter` which would be fine to reolve directly in the CF template (as it evaluates to a string), but CDK won't synth the template since `${Token[TOKEN.248]}` isn't a valid value for that enum.

I created a `CfnMapping` to try to do the same thing, but it still fails because it's not an issue of the template being invalid, it's that it won't even synth that param or mapping into a template.

Both of these fail with: `Invalid removal policy: ${Token[TOKEN.248]}`

```
    const removalPolicy = new CfnParameter(this, 'RepositoryRemovalPolicyParam', {
      description: `Removal policy for new Repositories. Default: ${RemovalPolicy.RETAIN}`,
      default: RemovalPolicy.RETAIN,
      allowedValues: Object.values(RemovalPolicy),
    }).valueAsString as RemovalPolicy;

    const newEcrRepositories: Repository[] = [];
    REPOS.forEach((repositoryName) =>
      newEcrRepositories.push(
        new Repository(this, `Repo-${repositoryName}`, {
          repositoryName,
          removalPolicy,
        })
      )
    );
```

```
    const removalPolicyParam = new CfnParameter(this, 'RepositoryRemovalPolicyParam', {
      description: `Removal policy for new Repositories. Default: ${RemovalPolicy.RETAIN}`,
      default: RemovalPolicy.RETAIN,
      allowedValues: Object.values(RemovalPolicy),
    }).valueAsString;

    const ecrMapping = new CfnMapping(this, 'EcrRepoRemovalPolicyMapping', {
      mapping: {
        [REMOVAL_POLICY_MAPPING_KEY]: Object.entries(RemovalPolicy).map(([key, value]) => ({ [key]: value })),
      },
    });

    const newEcrRepositories: Repository[] = [];
    REPOS.forEach((repositoryName) =>
      newEcrRepositories.push(
        new Repository(this, `Repo-${repositoryName}`, {
          repositoryName,
          removalPolicy: ecrMapping.findInMap(REMOVAL_POLICY_MAPPING_KEY, removalPolicyParam) as RemovalPolicy,
        })
      )
    );
```

**Comment by skinny85** [comment]
@john-kontralto try using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set these deletion policies based on CFN Parameters.

**Comment by john-kontralto** [comment]
> @john-kontralto try using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set these deletion policies based on CFN Parameters.

Yup, raw overrides would work, but I'm curious why not allow tokens in those kinds of checks? The API will fail if the provided values are invalid at deploy, so it seems pretty low risk.

**Comment by john-kontralto** [comment]
Looks like CloudFormation fails template validation as well on `DeletionPolicy` even if you use an escape hatch and override to anything other than a string literal, so looks like the only way to do this would be have explicitly defined resources for every value of the enum and then use CF Conditionals to deploy them conditionally. The issue is with CF and not CDK.

So if anyone else comes across this, that's the only way around it unless there's a change made to CF, and CDK needs these checks to prevent the CF template from failing validation. Don't override the template, it won't work.

**Comment by skinny85** [comment]
Good to know @john-kontralto , thanks for the update!
