### ISSUE TITLE
Obscure error message 'Bucket named 'bucket-name' exists, but not in account [object Object]. Wrong account?'

### ISSUE THREAD

**Issue by pmarrone** [aws/aws-cdk#6808]
When running CDK deploy trying to deploy assets in preexisting CDK buckets, created by the bootstrap process without the necessary s3:getBucketLocation permission, the deployment fails with a message like
Obscure error message 'Bucket named 'bucket-name' exists, but not in account [object Object]. Wrong account?'
Notice that the bucket does exist in the account, it's just a permission issue.

### Reproduction Steps
Theoretical yet, but it should happen when trying to make a deploy to an account which already contains the assets being deployed in S3 from a previous bootstrap (at least there's where we saw it happening).

It's very likely that this can be reproduce by doing the same as in https://github.com/aws/aws-cdk/issues/4039, but only removing the s3:getBucketLocation permission.

### Error Log

```
'Bucket named 'bucket-name' exists, but not in account [object Object]. Wrong account?'
```
## Environment

  - **CLI Version      :**
  - **Framework Version: 1.1.0
  - **OS               : Linux x64
  - **Language         : English

### Other

Checking the code in https://github.com/aws/aws-cdk/blob/a75f711aea3dac83c6feec885b7df9b14a39486e/packages/cdk-assets/lib/private/handlers/files.ts you can see that when there is a permissions error, this message will be shown. Also, account is sent as an object and it stringifies into [objest Object]

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @pmarrone 

I'm not sure i follow, are you running the `deploy` with an assumed role? Can you share how exactly? Are you runing the cdk commands from within an ec2 instance?

**Comment by iliapolo** [comment]
Hi @pmarrone - scratch my previous message, I understand what's happening. Indeed, the message is not clear enough.

Thanks for reporting this!

**Comment by pmarrone** [comment]
Hi @iliapolo . I'm trying to find how to reproduce this. Our problem was the following:
We deploy a codepipeline using the cdk with a role with admin privileges. One of the codepipe steps invokes the cdk itself to redeploy changed assets. Before, this step was run with admin rights (*:*).
While tightening the permissions for this step, the s3 privileges were reduced to the following
```
new iam.PolicyStatement({
   resources: ['arn:aws:s3:::cdktoolkit-stagingbudket-*'],
   actions: ['s3:*Object', 's3:ListBucket'],
})
```
This was not enough as it triggers the described error. It appears that this error response happens when the role has this permissions but lacks the s3:getBucketLocation permission.

**Comment by iliapolo** [comment]
Yeah gotcha. So basically would a nicer error message be suffice? In addition to documenting the necessary permissions as mentioned here: https://github.com/aws/aws-cdk/issues/4039

Did I understand correctly?

**Comment by iliapolo** [comment]
@pmarrone btw i managed to reproduce this easily by simply assuming a role from the command line using `aws sts assume-role`.

**Comment by pmarrone** [comment]
Nice. I was thinking if this makes sense. The required permission trigger the error using an action that does not seem to be used elsewhere to check the access to the bucket (say, it requires an extra permission to check that the permission exists even when it is not the permission that is required to perform operations on that bucket). Shouldn't this check be attempted only when an operation fails on the S3 bucket, such as publishing the asset? I failed to understand the ownership check.

**Comment by iliapolo** [comment]
Yeah i see what you're saying. Definitely makes sense. Ok, i'm prioritizing this bug and we will address it promptly. Keep an eye out here in the issue.  

@rix0rrr Can I have your take on this? It looks like this `getLocation` operation was recently added, but can actually break existing deployments since it requires a change to the role they might using. Is it just a pre-emptive check?

**Comment by cnilak** [comment]
Any update on this? I am still getting the same error, I even updated the bucket policy as below::
{
    "Version": "2012-10-17",
    "Id": "AccessControl",
    "Statement": [
        {
            "Sid": "UpdateBucketPolicy",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::{...acount id..}:root"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::bucketnamefordemo",
                "arn:aws:s3:::bucketnamefordemo/*"
            ]
        }
    ]
}

**Comment by oscarnevarezleal** [comment]
I can confirm the error is related to a lack of permissions as @pmarrone mentioned. I had a task definition complaining about the same problem. The policy below worked for my situation.

```
taskDefinition.addToTaskRolePolicy(
      new iam.PolicyStatement({
        resources: ["arn:aws:s3:::cdktoolkit-stagingbucket-*"],
        actions: ["s3:*Object", "s3:ListBucket", 's3:getBucketLocation'],
      })
    );
```

**Comment by moravcik** [comment]
Thank you @oscarnevarezleal, I was missing the `s3:getBucketLocation` action in my case

**Comment by iliapolo** [comment]
The obscure error message was resolved in https://github.com/aws/aws-cdk/pull/7022/. As far as the permissions, `GetBucketLocation` is a required action for the deployment. I've created this issue to follow up on documenting these permissions: https://github.com/aws/aws-cdk/issues/9863

**Comment by asween16** [comment]
Hi I am not sure I understand the fix to this problem. I am going through the AWS CDK Workshop. I am trying to do the deploy after creating the lambda and I am now seeing the same error. I deleted and re-added the bucket but still getting the wrong account error. 

Where do I fix the permissions? In the IAM role or in the CDK code?

Thanks

**Comment by vladm123** [comment]
Stumbled upon the same error message today, but not on `arn:aws:s3:::cdktoolkit-stagingbucket-*` as usually seen in tutorials.

1. cdk deployment failed with an error today without any change in the codebase: `Bucket named 'cdk-xxxxxxx-assets-*****-*****' exists, but not in account *****. Wrong account?`.
2. Permissions `s3:GetObject`, `s3:PutObject`, `s3:ListBucket`, `s3:GetBucketLocation` were already given to `arn:aws:s3:::cdktoolkit-stagingbucket-*` in the IAM role.
4. I added the same permissions to the `cdk-*-assets-*-*` bucket regex following the error message.
5. And it deployed again! :tada:

I can only explain it as a breaking change, since my deployments worked fine yesterday and stopped working today without changes, neither hitting the cdk deployment stack code, nor in the aws management console for that account.

`aws-cdk` version used: 1.136.0 (Scala).

cdk code to add, if interested (Scala):
```
PolicyStatement.Builder
.create()
.effect(Effect.ALLOW)
.actions(
    Seq(
    "s3:GetObject",
    "s3:PutObject",
    "s3:ListBucket",
    "s3:GetBucketLocation"
    ).asJava
)
.resources(
    Seq(
    "arn:aws:s3:::cdk-*-assets-*"
    ).asJava
)
.build()
```

**Comment by iamnotturner** [comment]
To use `sam-beta-cdk local start-api`, I had to set `"@aws-cdk/core:newStyleStackSynthesis": false`, because I received a random `KeyError` at synthesizing the app locally (as suggest here: https://github.com/aws/aws-sam-cli/issues/2968#issuecomment-865695246).

Setting `newStyleStackSynthesis` to false raised the same error you had when I deployed my Pipeline to AWS. Setting back `"@aws-cdk/core:newStyleStackSynthesis": true` fixed it for me.

**Comment by fabiopaiva** [comment]
I had this error after upgrading to CDK 2
it was trying to access a bucket with a name like "cdk-hash-assets-account-region" and my role only had permissions to access cdktoolkit-stagingbudket-*

**Comment by NeilSiao** [comment]
@fabiopaiva 
thx for your reply, After searching many hours, find out, i got the same problem with you, after cdk bootstrap my IAM role only had permissions to access cdktoolkit-stagingbudket-* and unable to access new bucket `cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}`

I had to go to iam console to manually modify exists policy, add new Resource  for permission
`
Resource": [
                "arn:aws:s3:::cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}",
                "arn:aws:s3:::cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}/*",
]
`

**Comment by vladikk** [comment]
Encountered the error today. In my case, not only the message has nothing to do with the actual issue (can't access bucket), but the cause of it can be found a few lines earlier in the log. It tries to assume the role that can access the bucket, fails, but continues anyway:

> [14:17:58] Assuming role failed: User: arn:aws:sts::[ACCOUNT]:assumed-role/ColPipelineStack-ColPipelineUpdatePipelineSelfMuta-[INSTANCE]/AWSCodeBuild-[ID] is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[ACCOUNT]:role/cdk-[INSTANCE]-file-publishing-role-[ACCOUNT]-[REGION]

> [14:17:58] Could not assume role in target account using current credentials User: arn:aws:sts::[ACCOUNT]:assumed-role/ColPipelineStack-ColPipelineUpdatePipelineSelfMuta-[INSTANCE]/AWSCodeBuild-[ID] is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[ACCOUNT]:role/cdk-[INSTANCE]-file-publishing-role-[ACCOUNT]-[REGION] . Please make sure that this role exists in the account. If it doesn't exist, (re)-bootstrap the environment with the right '--trust', using the latest version of the CDK CLI.

> current credentials could not be used to assume 'arn:aws:iam::[ACCOUNT]:role/cdk-[INSTANCE]-file-publishing-role-[ACCOUNT]-[REGION]', but are for the right account. Proceeding anyway.

**Comment by jmbelvar81** [comment]
In my case I found the problem was appearing when I defined the *"--bootstrap-bucket-name"* during the creation of a bootstrap stack *"customized"*.
 In this case, I did need create a bucket *"cdk-\*-assets-\*"* and during the execution of *cdk deploy* was rising the indicated error, although the bucket did exists in the account and region expected.Also the stagging bucket indicated with the flag was created without problems. This "duality" seemed to be the real reason of the problem in my case. I suspect that in some place into "the cdk implementation" the stagging bucket name is "hardcoded" according the expected pattern and ignoring the given flag value.

The solution in my case was remove the flag *"--bootstrap-bucket-name"* and then the stagging bucket was created automatically and the message *"Bucket named 'cdk-<qualifier>-assets-<account id>-<region>' exists, but not in account <accountid>. Wrong account?"* dissapeared.

As I commented previously, the pattern expected for the stagging bucket is 'cdk-\<qualifier\>-assets-\<account id\>-\<region\>'  
and the use with the flag  *"--bootstrap-bucket-name"*  and a different value seems being ignored and generate two problems:

- The bucket with required pattern is requested during bootstrap deployment, although you indicated a different one via the corresponding flag
- The message indicated at this thread appear when you create the bucket and deploy the cdk stack.


I hope this info can be useful to users with similar problems.

**Comment by tomoima525** [comment]
> Resource": [ "arn:aws:s3:::cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}", "arn:aws:s3:::cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}/*", ]

Also note that it's quite important to include both the directory name (`{directoryname}`) AND wildcard for the directory (`{directoryname}/*`). I forgot to add the former one and dumped a couple of hours investigating the issue

**Comment by LinoMejiaDC** [comment]
I run cdk deploy --profile myprofile --verbose.  --verbose help in debug. 

I identify that error was because policy access.  

I solved follow this steps: 

Step 1 
Create S3 bucked manually. 

step 2
give permision by CLI 

aws iam attach-role-policy --role-name xxxx --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess
aws iam attach-role-policy --role-name xxxx--policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess
aws iam attach-role-policy --role-name xxxx--policy-arn arn:aws:iam::aws:policy/AdministratorAccess
aws iam attach-role-policy --role-name xxx--policy-arn arn:aws:iam::aws:policy/AdministratorAccess
```

#### Step 3: Update S3 Bucket Policy

Ensure the S3 bucket policy allows access to the necessary roles. Here’s an example policy that allows access:

1. **Go to the S3 console**.
2. **Select your bucket (`cdk-hnb659fds-assets-985275817835-sa-east-1`)**.
3. **Navigate to the Permissions tab**.
4. **Edit the Bucket Policy** to include the following JSON:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::985275817835:role/[bucked_name]",
          "arn:aws:iam::985275817835:role/cdk-hnb659fds-file-publishing-role-[user-id]-[Region]"
,

        ]
      },
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::[BUCKED NAME]",
        "arn:aws:s3:::[BUCKED NAME]/*"
      ]
    }
  ]
}
```

### Retry the Deployment

After updating the IAM role policies and S3 bucket policy, retry the deployment:

1. **Re-run Bootstrap** (if necessary):

   ```bash
   cdk bootstrap aws://USERID/REGION--profile NAME--force
   ```

2. **Deploy the CDK Stack**:

   ```bash
   cdk deploy --profile myprofile--verbose
   ```
and it worked.
